// ZALAVAD PATIDAR BUSINESS DIRECTORY DATA

var directoryData = [
  {
    fullName: "Varmora Jigar Manharbhai",
    whatsapp: "9409490194",
    village: "Sara",
    taluka: "Muli",
    bloodGroup: "B+",
    businessName: "Bhimani International Llp",
    businessType: "Export",
    email: "",
    website: "",
    address: "Mahendranagar Chokdi",
    visitingCard: ""
  },
  {
    fullName: "Kachrola Prakash Keshavjibhai",
    whatsapp: "9825829695",
    village: "Tikar",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Varmora Group",
    businessType: "Ceramic Tiles And Bathware",
    email: "prakashpatel@varmora.com",
    website: "www.varmora.com",
    address: "Varmora Grainito Pvt.Ltdat-Dhuva .Nh8a Wankaner Morbi Highway",
    visitingCard: ""
  },
  {
    fullName: "Sanghani Rajesh Rameshbhai",
    whatsapp: "8264982473",
    village: "Danawada",
    taluka: "Muli",
    bloodGroup: "B+",
    businessName: "Pramukh Electronics & Alexa International",
    businessType: "Electronics & Tiles",
    email: "rajeshsanghani421@gmail.com",
    website: "",
    address: "Rr8c+82w, Moonnagar Street Number 4, Rajnagar, Sardar Nagar, Morbi, Gujarat 363641",
    visitingCard: ""
  },
  {
    fullName: "Rakesh Kumar Gangaram Bhai Kunpara",
    whatsapp: "9638439321",
    village: "Chamaraj",
    taluka: "Wadhwan",
    bloodGroup: "O+",
    businessName: "Maruti Electric And Inverter Service",
    businessType: "Electric",
    email: "rp3032734@gmail.com",
    website: "",
    address: "Nani Kenal Road  Sanraiz Vila Shop No 110",
    visitingCard: "https://drive.google.com/open?id=19z-WH5ahVxRh6gSIH8tjbseGk6pyHm02"
  },
  {
    fullName: "Makasana Dhaval Parbhubhai",
    whatsapp: "7990849787",
    village: "Moti Malvan",
    taluka: "Dhrangdhra",
    bloodGroup: "O+",
    businessName: "Clone Ceramic",
    businessType: "Tiles Teding And Cuting",
    email: "",
    website: "",
    address: "Halvad Rode .Hariom Park. Mahendarnagar",
    visitingCard: "https://drive.google.com/open?id=1bwEszAMHPYzThC871lQBDhE1MSwyZE7M"
  },
  {
    fullName: "Gopani Prayag Ashok Bhai",
    whatsapp: "7984776859",
    village: "Nava Ghanshyamgadh",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Digital Diva",
    businessType: "Digital Marketing Services",
    email: "prayaggopani29@gmail.com",
    website: "www.digital-diva.com",
    address: "S-6, 2nd Floor, Shiv Plaza, Nani Canal Road, Opp. Kishan Park, Panchasar Road, Morbi.",
    visitingCard: "https://drive.google.com/open?id=1OydA9qyl-p7hlsd-9J58B4C3qou02uFj"
  },
  {
    fullName: "Kavar Montu Ranchhodbhai",
    whatsapp: "9428718254",
    village: "Khodu",
    taluka: "Wadhwan",
    bloodGroup: "B+",
    businessName: "Patidar Impex & Solution",
    businessType: "Barcode Labels , Sticker",
    email: "montukavar@gmail.com",
    website: "",
    address: "Manendranagar, Morbi",
    visitingCard: ""
  },
  {
    fullName: "Vidja Nilesh Bhai Jasmatbhai",
    whatsapp: "9737803202",
    village: "Mangadh",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Krometi Pepar",
    businessType: "Pepar",
    email: "nilesh3202@gmail.com",
    website: "",
    address: "Halvad Rod",
    visitingCard: "https://drive.google.com/open?id=1gX9Uk-CXY-61ieN0NIw8tvGFqVSpw2xd"
  },
  {
    fullName: "Varmora Bhagvanjibhai Manji Bhai",
    whatsapp: "9879993920",
    village: "Sara",
    taluka: "Muli",
    bloodGroup: "B+",
    businessName: "Chi Fasteners",
    businessType: "Treading Nut Bolt All Type",
    email: "chi.fasteners@gmail.com",
    website: "",
    address: "C-5 Hari Chembers Trajpar Char Rasta Morbi Gujarat 363642",
    visitingCard: "https://drive.google.com/open?id=1RyI-uLizwMAzAC07D_HzQVLmumYm7QaE"
  },
  {
    fullName: "Koladara Bhavesh Karsan Bhai",
    whatsapp: "9638496987",
    village: "Nana Ankevadiya",
    taluka: "Lakhtar",
    bloodGroup: "O+",
    businessName: "Shiv Shakti Enterprises/ Trding",
    businessType: "Conveyor Belt/ Ind.Oil/Grese",
    email: "bhaveshkoladara1987@gmail.com",
    website: "",
    address: "Pinak Chembur Riyal Plaza Ni Same Lalpar",
    visitingCard: ""
  },
  {
    fullName: "Mitul Kantilal Patel",
    whatsapp: "9913561816",
    village: "Nava Ghanshyamgadh",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Paper Mill",
    businessType: "Manufacturers",
    email: "2.opaperproduct@gmail.com",
    website: "",
    address: "Aniyari,Jetpar",
    visitingCard: ""
  },
  {
    fullName: "Jivani Ashish Janakbhai",
    whatsapp: "9687094549",
    village: "Dhrangadhra",
    taluka: "Dhrangdhra",
    bloodGroup: "",
    businessName: "Jog Ceramic",
    businessType: "Ceramic Sanitaryware Trading",
    email: "ajj2711@gmail.com",
    website: "",
    address: "",
    visitingCard: ""
  },
  {
    fullName: "Jivani Dhaval Janakbhai",
    whatsapp: "9904994446",
    village: "Dhrangadhra",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "Rotto Bathware",
    businessType: "Sanitaryware Wholesaler",
    email: "dhaval2jivani@gmail.com",
    website: "",
    address: "Rotto Bathware, B/H Maruti Suzuki Workshop, Opp. Pipli Village, Jetpar-Pipli Road, Morbi-2",
    visitingCard: "https://drive.google.com/open?id=1EpYnr1ZsAQ5zO5d7yDzPP47JGM4vzpu5"
  },
  {
    fullName: "Dharmendra P Bhadja",
    whatsapp: "8866323222",
    village: "Merupar",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Rotto Tiles",
    businessType: "Ceramic",
    email: "dpbhadja@gmail.com",
    website: "rotto tiles.com",
    address: "Lalper 8a National Hiway",
    visitingCard: "https://drive.google.com/open?id=1D5MLOFRYXUERDtho1cpN3WeYUGEa9ref"
  },
  {
    fullName: "Rajnikant Mansukhbhai Jagodana",
    whatsapp: "9016316393",
    village: "Thala",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "Swastik Plastic & Royal Polyplast Llp",
    businessType: "Reprocess Plastic And Plastic Chair And Furniture",
    email: "rajni.jagodana@gmail.com",
    website: "www.royalpolyplastllp.com",
    address: "27-National Highway, Ravapar Nadi Road, Near Sarvoday Hotel, Morbi - 363642, Gujarat, India.",
    visitingCard: ""
  },
  {
    fullName: "Marvaniya Vraj Rohit Bhai",
    whatsapp: "8780037637",
    village: "Samli",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Bhimani International Llp",
    businessType: "Import Export",
    email: "",
    website: "",
    address: "",
    visitingCard: ""
  },
  {
    fullName: "Patel Rupesh Lakshmanbhai",
    whatsapp: "9998910340",
    village: "Methan",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "Professor",
    businessType: "Government Job",
    email: "rlp131277@gmail.com",
    website: "",
    address: "",
    visitingCard: ""
  },
  {
    fullName: "Varmora Rahul Kumar Harjivan Bhai",
    whatsapp: "8460032370",
    village: "Sara",
    taluka: "Muli",
    bloodGroup: "B+",
    businessName: "William John'S Pizza Mahendra Nagar",
    businessType: "Food",
    email: "rahulvarmora@gmail.com",
    website: "",
    address: "Mh",
    visitingCard: ""
  },
  {
    fullName: "Varmora Bhailal Bhai Lakhman Bhai",
    whatsapp: "9925954804",
    village: "Ghutu",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Gurukrupa Enterprise And Tiles Cuttings",
    businessType: "Tiles Cutting And Selling",
    email: "",
    website: "",
    address: "",
    visitingCard: ""
  },
  {
    fullName: "Harjivan Bhai C Varmora",
    whatsapp: "8460032370",
    village: "Sara",
    taluka: "Muli",
    bloodGroup: "B+",
    businessName: "Shree Umiya Novelty Parotha House",
    businessType: "Food Restaurant",
    email: "rahulvarmora@gmail.com",
    website: "",
    address: "Citi Point Complex Near Mahendranagar Morbi 2",
    visitingCard: ""
  },
  {
    fullName: "Patel Hitesh Chamanbhai",
    whatsapp: "9726801525",
    village: "Samli",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Linum Ceramic",
    businessType: "Construction",
    email: "karmkrushi@gmail.com",
    website: "",
    address: "Morbj",
    visitingCard: ""
  },
  {
    fullName: "Aervadiya Lalit Bhanjibhai",
    whatsapp: "9726421212",
    village: "Mangadh",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Impera Ceramic",
    businessType: "Wall Tiles Manufacturer",
    email: "lalit@imperaceramic.com",
    website: "www.imperaceramic.com",
    address: "At. Rangpar, Jetpar Road, Morbi",
    visitingCard: "https://drive.google.com/open?id=1WVGo3v12IU5WmVa1pplnCzj3W-WN4yt2"
  },
  {
    fullName: "Varmora Jay Bharatbhai",
    whatsapp: "9824209436",
    village: "Sara",
    taluka: "Muli",
    bloodGroup: "",
    businessName: "Jabaco Overseas Llp",
    businessType: "Export Business",
    email: "jayvarmora5357@gmail.com",
    website: "www.jabaco.in",
    address: "Shivalik Complex, Mahendranagar Circle, Morbi-363642",
    visitingCard: ""
  },
  {
    fullName: "Kaila Harshadkumar Ambarambhai",
    whatsapp: "9825296990",
    village: "Ishwarnagar",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Simola Tiles",
    businessType: "Marketing",
    email: "harshadkaila.80@gmail.com",
    website: "",
    address: "",
    visitingCard: ""
  },
  {
    fullName: "Bhojani Sanjaybhai Mansukhbhai",
    whatsapp: "9924581646",
    village: "Tikar",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Vedant School Morbi",
    businessType: "School",
    email: "sanjaybhojani7301@gmail.com",
    website: "",
    address: "Vavadi Morbi",
    visitingCard: ""
  },
  {
    fullName: "Satapara Jignesh Chamanbhai",
    whatsapp: "7359715147",
    village: "Surendranagar",
    taluka: "Wadhwan",
    bloodGroup: "B+",
    businessName: "Universal Solution",
    businessType: "Coal, Soda Ash, Marble Powder, Fastners",
    email: "jignesh.universalmaterial@gmail.com",
    website: "",
    address: "Empire 36, Op Fern Residency, Mahendra Nagar, Morbi-2",
    visitingCard: ""
  },
  {
    fullName: "Makasna Vijedrbhai Amarsibhai",
    whatsapp: "9687278393",
    village: "Nava Devaliya",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Construction",
    businessType: "Building Contractors",
    email: "",
    website: "",
    address: "Halvad, Morbi",
    visitingCard: ""
  },
  {
    fullName: "Khavadiya Mahesh Chhagan Bhai",
    whatsapp: "9909111554",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Khavadiya Trending Co.",
    businessType: "Anaj Kariyana",
    email: "",
    website: "",
    address: "A27, Marketing Yard Morbi.",
    visitingCard: ""
  },
  {
    fullName: "Dhanjibhai Valjibhai  Dalsaniya",
    whatsapp: "9825796210",
    village: "Ishwarnagar",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Oryn Minchem",
    businessType: "Bopp Tape Roll",
    email: "preetdalsaniya@gmail.com",
    website: "",
    address: "Morbi",
    visitingCard: ""
  },
  {
    fullName: "Detroja Rajeshkumar Kalubhai",
    whatsapp: "9913720609",
    village: "Vankiya",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Shubhlaxmi Cranotech Llp",
    businessType: "Eot Crane Manufacturer,  Industrial Crane Manufacture All Type Of Fabrication Work",
    email: "shubhlaxmicranotechllp@gmail.com",
    website: "www.shubhlaxmicranes.com",
    address: "Survey No - 345/-2, Dhareshwar Mahadev Temple Road, Morbi - Halvad High Way , At Andarana, Morbi, Gujrat - 363642",
    visitingCard: "https://drive.google.com/open?id=1_TP_z7S26m_REyE7xODMLvIzOc4mMPuW"
  },
  {
    fullName: "Law Pareshkumar Jayantilal",
    whatsapp: "9998327972",
    village: "Gujarvadi",
    taluka: "Dhrangdhra",
    bloodGroup: "O+",
    businessName: "Florice Polychem Llp",
    businessType: "Ceramic Binder",
    email: "floricepolychem@gmail.com",
    website: "",
    address: "Rajkot Kandla Bypass, Swaminarayan Gurakul Road,Dharmpur Road",
    visitingCard: ""
  },
  {
    fullName: "Khavadiya Sandip Muljibhai",
    whatsapp: "9725555594",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "P.D.Patel & Sans",
    businessType: "All Commodities Sels & Parches",
    email: "",
    website: "",
    address: "A31 Marketing Yard Sanala Road",
    visitingCard: "https://drive.google.com/open?id=1ip4AWMtQE1XjiEjpvWO0esQUDM6GPI9k, https://drive.google.com/open?id=16tLp6ScThRJ1OyKlvrIbuEIlXPFWAAUv"
  },
  {
    fullName: "Viramgama Harshad Bhai Daya Bhai",
    whatsapp: "9328765988",
    village: "Moti Malvan",
    taluka: "Dhrangdhra",
    bloodGroup: "B-",
    businessName: "Bajrang Aluminium Seksan",
    businessType: "Aelyumimiyam Seksan",
    email: "",
    website: "",
    address: "Mahendra Nagar Chokdi Hadvad Rod Prabhat Chebar",
    visitingCard: ""
  },
  {
    fullName: "Chhatrola Jaykumar Manaharlal",
    whatsapp: "9998458317",
    village: "Limbadi",
    taluka: "Limbadi",
    bloodGroup: "B+",
    businessName: "Deputy Engineer, Getco",
    businessType: "Goverment Job",
    email: "alwaysjaypatelelec@gmail.com",
    website: "",
    address: "",
    visitingCard: ""
  },
  {
    fullName: "Sersiya Ashvin Cunilal",
    whatsapp: "9909068121",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Kesri Hotal",
    businessType: "Fud",
    email: "",
    website: "",
    address: "",
    visitingCard: ""
  },
  {
    fullName: "Kasodiya Yogesh Thakarshibhai",
    whatsapp: "9737146900",
    village: "Soladi",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "Kp Label",
    businessType: "All Types Of  Label",
    email: "kasodiyayogesh8@gmail.com",
    website: "not available",
    address: "Uma Residency, Near By Iti, Ghuntu Road.",
    visitingCard: "https://drive.google.com/open?id=1-gpZSwg9uk8k_r3pMWPpwrb4BiEMHh21"
  },
  {
    fullName: "Varmora Kalpesh",
    whatsapp: "8758711311",
    village: "Ranmalpur",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Bhagwati Best Chemicals",
    businessType: "Nano Chemical",
    email: "kalpesh9978940721@gmail.com",
    website: "",
    address: "Mahendranagar, Morbi",
    visitingCard: ""
  },
  {
    fullName: "Harsh Patel",
    whatsapp: "8530402322",
    village: "Juna Devaliya",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Genesis Enterprise",
    businessType: "Chemical & Tiles Trading",
    email: "genesisenterprisee@gmail.com",
    website: "",
    address: "S-12,Hemratna Chember,Nr.Trajpar Chowkdi,8-A National Highway,Morbi-363641 Gujarat, India",
    visitingCard: "https://drive.google.com/open?id=1GBAx_BccOC3aKl9EEML1n3pzjna9WNlC"
  },
  {
    fullName: "Araniya Alpesh Rashikbhai",
    whatsapp: "9537777058",
    village: "Tikar",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Mr.Refilling",
    businessType: "Cartridge Refilling And Printer Repair",
    email: "apatel0233@gmail.com",
    website: "",
    address: "212 Patel Shoping Super Market Sanala Road Morbi",
    visitingCard: "https://drive.google.com/open?id=1g6v9N0VmyEda2sm9Vtk-TfXTEEefMBsn"
  },
  {
    fullName: "Khavadiya Sandip Mulajibhai",
    whatsapp: "9725555594",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Goral Agri Process",
    businessType: "Sotex Plant All Commodity",
    email: "",
    website: "",
    address: "Bhimnath Mahadev Road Opp.Lajai Village",
    visitingCard: "https://drive.google.com/open?id=1TmXRHY5SuFDEQKf1_92zhYVxbGEdqkFL"
  },
  {
    fullName: "Kunapara Vijay Bhai Nagar Bhai",
    whatsapp: "9825281350",
    village: "Sara",
    taluka: "Muli",
    bloodGroup: "O+",
    businessName: "Selzia Impex Romatiriyal Backwash Powder",
    businessType: "Backwash Powder  Ro Megnesite Powder",
    email: "kunparavijaybhai@gmail.com",
    website: "",
    address: "Bharat Nagar Office",
    visitingCard: ""
  },
  {
    fullName: "Bhavesh Bhai  Bechada",
    whatsapp: "7285815115",
    village: "Dhrangadhra",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "Aqua Cera",
    businessType: "Senitriware",
    email: "bhaveshpatel15115@gmail.com",
    website: "",
    address: "Lilapar Chikdi",
    visitingCard: ""
  },
  {
    fullName: "Manishkumar Baldevbhai Aervadiya",
    whatsapp: "9909458292",
    village: "Tikar",
    taluka: "Halvad",
    bloodGroup: "A+",
    businessName: "Vnc Inpex",
    businessType: "All Type Nano Polishing Ped And Liquid",
    email: "vihanimpex157@gmail.com",
    website: "",
    address: "Ceramic Plaza-1, 8-A, N.H, Morbi-363642",
    visitingCard: "https://drive.google.com/open?id=1VxsSiouem5rYD0jI66r60cZMIUkpj3Uz"
  },
  {
    fullName: "Arvadiya Kiranbhai Ishwarbhai",
    whatsapp: "9427709177",
    village: "Tikar",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Shakti Oil Industries",
    businessType: "Ground Nut Oil",
    email: "kiranaervadia@gmail.com",
    website: "",
    address: "At- Andarna, Ta. Morbi",
    visitingCard: "https://drive.google.com/open?id=1MCll-qzI4gZ123abYp85ozYUfzh5W7Lp"
  },
  {
    fullName: "Khandivar Ashvin Sukhadevbhai",
    whatsapp: "9099090941",
    village: "Ingorala",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Indicera World",
    businessType: "Export Import",
    email: "info@indicera.co.in",
    website: "www.indiceratiles.com",
    address: "Morbi",
    visitingCard: "https://drive.google.com/open?id=1JQfpCByX_MaYi77qN9H8Y5OTi-Pv0Lam"
  },
  {
    fullName: "Kiran Baldevbhai Parejiya",
    whatsapp: "7359888628",
    village: "Danawada",
    taluka: "Muli",
    bloodGroup: "AB+",
    businessName: "Angelone",
    businessType: "Share Bajaar , Finance ,Investment , Stock Market",
    email: "",
    website: "",
    address: "228, 2nd Floor  , Kohinoor Complex, Kenal Road , Morbi",
    visitingCard: ""
  },
  {
    fullName: "Gothi Dhaval Jivarajbhai",
    whatsapp: "7990930211",
    village: "Juna Ghanshyamgadh",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "Jb Impex",
    businessType: "Raw Material ( Back Wash )",
    email: "jbimpex1996@gmail.com",
    website: "",
    address: "Office No 5&6, Ground Floor, Near Iti College, Bharat Nagar Morbi 2",
    visitingCard: ""
  },
  {
    fullName: "Khavadiya Haresh Chaganbhai",
    whatsapp: "9879688898",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Zalavad Trading",
    businessType: "Anaj Kariyanu",
    email: "",
    website: "",
    address: "A27 Marketing Yard Sanala Road Morbi",
    visitingCard: "https://drive.google.com/open?id=15sVFYLQV_SG_vEezRGqVvklMsyC5TZgX"
  },
  {
    fullName: "Jalariya Kantilal Valjibhai",
    whatsapp: "9979473851",
    village: "Manpur",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "Vijayvargiy Electric",
    businessType: "Electric Shop",
    email: "",
    website: "",
    address: "Shivaji Weight Bridge Baju Ma, Dhuva, Morbi",
    visitingCard: ""
  },
  {
    fullName: "Jakashaniya Kaushik Mahadevbhai",
    whatsapp: "8866773982",
    village: "Ramgadh",
    taluka: "Dhrangdhra",
    bloodGroup: "",
    businessName: "Akshar Ceramic Mall",
    businessType: "Tiles Ritelar",
    email: "aksharenterprise.in@gmail.com",
    website: "",
    address: "Akshar Ceramic Mall , Mahendra Nagar Chowkdi, Morbi-2",
    visitingCard: "https://drive.google.com/open?id=11tlMPdRQn_mcKv2Fyz9Nrgd7mtaTto39"
  },
  {
    fullName: "Rajnish Araniya",
    whatsapp: "9925644707",
    village: "Vakiya",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Mechwell Engineering",
    businessType: "Machine Manufacturers",
    email: "jaydeepengineering@gmail.com",
    website: "",
    address: "8, A National Highway, Timbdi Patiya, Morbi- 363642",
    visitingCard: ""
  },
  {
    fullName: "Khavadiya Nilesh Karamshibhai",
    whatsapp: "9825628251",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Gnapath School",
    businessType: "School",
    email: "",
    website: "",
    address: "",
    visitingCard: ""
  },
  {
    fullName: "Surani Meet Jitendrabhai",
    whatsapp: "7575011271",
    village: "Bavli",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "Mangalam Clinic",
    businessType: "Clinic",
    email: "meetpatel3707@gmail.com",
    website: "",
    address: "",
    visitingCard: ""
  },
  {
    fullName: "Anilkumar Shantilal Malvaniya",
    whatsapp: "9898120978",
    village: "Samli",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Jayshakti Multy Service",
    businessType: "All Type Online Work",
    email: "anilpatel2786@gmail.com",
    website: "",
    address: "1 Branch...Opp Cng Gas Pump, Mahendranagar Morbi. 2nd Branch   Behind Avadh Pan Near Bus Stop Charadva",
    visitingCard: ""
  },
  {
    fullName: "Keraliya Mileshkumar Shankarlal",
    whatsapp: "9824262526",
    village: "Limli",
    taluka: "Muli",
    bloodGroup: "O+",
    businessName: "Keraliya & Associate",
    businessType: "Chartered Accountant",
    email: "mileshkeraliya1986@gmail.com",
    website: "",
    address: "Office No-320, Landmark Arcade, Near Vinayak Honda Showroom, Sanala Road, Morbi-363641.",
    visitingCard: "https://drive.google.com/open?id=1cEYX50gF_Wc13jErv413LRBisLZEbSFW"
  },
  {
    fullName: "Sherasiya Bhavesh Arvindbhai",
    whatsapp: "9408719651",
    village: "Ajitgadh",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Id Enterprise",
    businessType: "Tiles & Sanitaryware Trading",
    email: "identerprise20@gmail.com",
    website: "",
    address: "Morbi",
    visitingCard: "https://drive.google.com/open?id=1HCN94R4ST-pSfrzz8A2MPBdRsjikpO7j"
  },
  {
    fullName: "Makasana Mayank Pravinbhai",
    whatsapp: "9909988455",
    village: "Kadiyana",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Sunhearrt Ceramik",
    businessType: "Tiles Manufacturing",
    email: "mayank@sunhearrt.com",
    website: "www.sunhearrt.com",
    address: "8-A National Highway , Dhuva",
    visitingCard: ""
  },
  {
    fullName: "Fultariya Atul Bhai Kashvji Bhai",
    whatsapp: "9726126501",
    village: "Pratapgarh",
    taluka: "Halvad",
    bloodGroup: "A+",
    businessName: "Hi Gloss Nano Technology",
    businessType: "Row Material",
    email: "higlossnanotec@gmail.-com",
    website: "",
    address: "Timbadi Morbi",
    visitingCard: ""
  },
  {
    fullName: "Bhorniya Rajnikant Tribhovan Bhai",
    whatsapp: "9909626745",
    village: "Juna Devaliya",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Ceramic Contractor",
    businessType: "Leber Contractor",
    email: "rajni2057patel@mail.com",
    website: "",
    address: "Morbi",
    visitingCard: ""
  },
  {
    fullName: "Patel Rajendra Kumar Bachubhai",
    whatsapp: "9428917760",
    village: "Juna Devaliya",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Sanitary Ware Painter",
    businessType: "Painter Contract",
    email: "wwwraj78061@gmail.com",
    website: "9428917760",
    address: "Rangpar. Raj Tranding",
    visitingCard: ""
  },
  {
    fullName: "Dharmendra Araniya",
    whatsapp: "9879485400",
    village: "Vankiya",
    taluka: "Halvad",
    bloodGroup: "A+",
    businessName: "Ditya Agri Trade",
    businessType: "All Types Of Commodity Items Trading",
    email: "",
    website: "",
    address: "At- Vankiya, Halvad",
    visitingCard: "https://drive.google.com/open?id=1puzer2JblFUf20fE0rc29trIQ98-mOFP"
  },
  {
    fullName: "Sanghani Akash Nandlal Bhai",
    whatsapp: "9067834725",
    village: "Nava Ghanshyamgadh",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Sidhivinayak Coal",
    businessType: "Coal Trading",
    email: "akashsanghani94@gmail.com",
    website: "",
    address: "Timbdi  Morbi",
    visitingCard: "https://drive.google.com/open?id=1PWkA4PzBxFZWaR_DOjlSeZS6PIPu9k_O"
  },
  {
    fullName: "Jashapara Ravikumar Maganbhai",
    whatsapp: "9979298787",
    village: "Juna Devaliya",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Sadguru Industries",
    businessType: "Glass Powder",
    email: "patelravi4415@gmail.com",
    website: "",
    address: "Sunfield Ceramic,Juna Ghutu Road,Morbi",
    visitingCard: "https://drive.google.com/open?id=1Nvxx6haBtlTfdtU3KgAfsAo85fry52Am"
  },
  {
    fullName: "Karodiya Tusharkumar Dhanjibhai",
    whatsapp: "8200362198",
    village: "Ranjitgadh",
    taluka: "Halvad",
    bloodGroup: "AB+",
    businessName: "Gurukrupa Enterprises",
    businessType: "Treding Tiles & Sanitaryware",
    email: "tusharkarodiya83471@gmail.com",
    website: "",
    address: "Shop No.411, Shivam Complex, Opp Trade Center, Halvad Road, Mahender Nagar, Morbi 2",
    visitingCard: ""
  },
  {
    fullName: "Patel Dharmendra T",
    whatsapp: "9979844415",
    village: "Juna Devaliya",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Indian Roadlines",
    businessType: "Transport",
    email: "indianroadlinesmorbi@gmail.com",
    website: "",
    address: "Opposite Cng Ges Pump, Mahendranagar Nagar Chokdi , Halvad Road,  Morbihalvad Road Morbi - 363642",
    visitingCard: "https://drive.google.com/open?id=1xRwe-GElHX_PbZXx6Q9E_abZ3HpBfLYh"
  },
  {
    fullName: "Sherasiya Bhavesh Arvindbhai",
    whatsapp: "9408719651",
    village: "Ajitgadh",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Id Enterprise",
    businessType: "Colloidal Silica Solution",
    email: "identerprise20@gmail.com",
    website: "",
    address: "Morbi",
    visitingCard: "https://drive.google.com/open?id=1AFYxtCM7Mi7-Mvrh6i0SC8MTxecALG4J"
  },
  {
    fullName: "Ghumaliya Ramnik Bhai Jaynti Bhai",
    whatsapp: "9913993125",
    village: "Gujarvadi",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "Gopinath Motars",
    businessType: "Own",
    email: "gopinath1745@gmail.com",
    website: "",
    address: "Behind Shivam Hospital, Mahendranagar",
    visitingCard: "https://drive.google.com/open?id=1MiMZu3XZY7BWG9aO4zsIg8kzT1qFakaq"
  },
  {
    fullName: "Makasana Nikunj Ghanshyambhai",
    whatsapp: "9724761461",
    village: "Ghanshyamgadh",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Ceramic Canteen",
    businessType: "Canteen",
    email: "nikunjmakasana9@gmail.com",
    website: "",
    address: "Landecor Ceramic Sultanpar Road, Wakaner Highway",
    visitingCard: ""
  },
  {
    fullName: "Patel Mehul Tribhovanbhai",
    whatsapp: "9902511890",
    village: "Kuntalpur",
    taluka: "Muli",
    bloodGroup: "AB+",
    businessName: "Saanvi Ceramic",
    businessType: "Tiles",
    email: "saanviceramics@gmail.com",
    website: "",
    address: "",
    visitingCard: "https://drive.google.com/open?id=1-YV-EtcS0_8959WZPdVDI6ItT3S67d2J, https://drive.google.com/open?id=1L6b-Hb_lWVvKkBs4A4w4Ef8ocZEUyHzr"
  },
  {
    fullName: "Hulani Mukund Ganeshbhai",
    whatsapp: "9586300993",
    village: "Mangadh",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Cerabizz Corporation",
    businessType: "Tiles & Sanitary Trading",
    email: "cerabizzcorporation00993@gmail.com",
    website: "",
    address: "Dharamgold Complex , Near Old Kuber Cinema , 8-A National Highway Morbi",
    visitingCard: "https://drive.google.com/open?id=1FM100UK_W2sCTkYUn7CspGr_xCsCh_l4"
  },
  {
    fullName: "Aghara Pravinbhai Tribhovanbhai",
    whatsapp: "9825448598",
    village: "Survadar",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "K B Corporation",
    businessType: "Chemical",
    email: "deepaghara7654@gmail.com",
    website: "",
    address: "Housing Board, Morbi 2",
    visitingCard: ""
  },
  {
    fullName: "Dalsaniya Maheshbhai Maganbhai",
    whatsapp: "7016866566",
    village: "Halvad",
    taluka: "Halvad",
    bloodGroup: "A+",
    businessName: "La Ceramica",
    businessType: "Tile Trading",
    email: "maheshpatel2587@gmail.com",
    website: "",
    address: "201 Akshar Business Center Rafadiya",
    visitingCard: ""
  },
  {
    fullName: "Dalsaniya Darshankumar Gunvantbhai",
    whatsapp: "9913155556",
    village: "Gujarvadi",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "Aavkar Hydraulic Pipe& Forclip",
    businessType: "Hydraulic",
    email: "dalsaniyadarshan2@gmail.com",
    website: "",
    address: "Jetpar Pipli Road",
    visitingCard: ""
  },
  {
    fullName: "Makasana Vijaykumar Ghanshyambhai",
    whatsapp: "9924052326",
    village: "Nava Ghanshyamgadh",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Union Bank Of India",
    businessType: "Service In Bank",
    email: "",
    website: "",
    address: "",
    visitingCard: ""
  },
  {
    fullName: "Loriya Amit Thobhan Bhai",
    whatsapp: "9879309814",
    village: "Vaghagadh",
    taluka: "Dhrangdhra",
    bloodGroup: "O+",
    businessName: "Teacher",
    businessType: "Gyanpath Vidhyalay Partner",
    email: "amitloriya@gamil.com",
    website: "-",
    address: "New Gujarat Housing Board Morbi",
    visitingCard: ""
  },
  {
    fullName: "Maravaniya Prayagkumar Talsibhai",
    whatsapp: "9638099899",
    village: "Samli",
    taluka: "Halvad",
    bloodGroup: "A-",
    businessName: "Bhuvneshwar Pack Print",
    businessType: "Manufacturer Of All Types Of Corrugated Box",
    email: "prayagmaravaniya@gmail.com",
    website: "",
    address: "Lakhadhirpur Road, 8-A National Highway, Morbi - 2.",
    visitingCard: "https://drive.google.com/open?id=1Pdqyu9ACjgqHHm7XFX02B6OuEvJtUmKd"
  },
  {
    fullName: "Varmora Dhavalkumar Balvantray",
    whatsapp: "9033429800",
    village: "Sara",
    taluka: "Muli",
    bloodGroup: "B+",
    businessName: "Iyota Tiles Llp",
    businessType: "Ceramic Wall Tiles",
    email: "varmora_dhaval@yahoo.com",
    website: "",
    address: "Dhuva Wankaner",
    visitingCard: "https://drive.google.com/open?id=1XsZta2-C1j_hpTDtiLghQKEHnu0AIlxQ"
  },
  {
    fullName: "Dalsaniya Jayeshbhai Khimjibhai",
    whatsapp: "9904545555",
    village: "Kidi",
    taluka: "Dhrangdhra",
    bloodGroup: "O+",
    businessName: "Swell Granito Llp",
    businessType: "Ceramic",
    email: "jashdalsaniya@gmail.com",
    website: "",
    address: "Sartanpar Road Ratavirda Wankaner",
    visitingCard: "https://drive.google.com/open?id=1MsfObBFfZFCkntq1ILFPfMCVmPXpPGes"
  },
  {
    fullName: "Lalit Kumar Sukhdev Bhai Khandivar",
    whatsapp: "9925699376",
    village: "Ingorala",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Patidar Stationery & Graphics",
    businessType: "Ceramic & Office Statonery & Printing Solution",
    email: "lalitkhandivar@gmail.com",
    website: "",
    address: "Dharti Tower, Near Old St Stand, Sardar Road Morbi",
    visitingCard: "https://drive.google.com/open?id=1b4XF_pkdZ36h-rvPGGvjRh8mkpJKBf29"
  },
  {
    fullName: "Vidja Jayntibhai Ramjibhai",
    whatsapp: "9925173240",
    village: "Nava Devaliya",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Classic Auto Mobiles",
    businessType: "All Car Spare Parts",
    email: "vishalvidja3727@gmail.com",
    website: "",
    address: "Gidc Opp Renault Showroom Near Rewa Township Sanala Road Morbi-1",
    visitingCard: ""
  },
  {
    fullName: "Khavadiya Jay Laljibhai",
    whatsapp: "6353529355",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Israel Seeds Corporation",
    businessType: "All Type Of Seeds Manufacturer",
    email: "israelseedscorporation@gmail.com",
    website: "",
    address: "*Israel Seeds Corporation*  Sr.No 613, At Po :- Medrapura (Kotadi) Behind Jay Prabhu Cotton Ind. Vijapur-Mehsana Highway Ta:- Vijapur  Do:-Mehsana",
    visitingCard: ""
  },
  {
    fullName: "Nandana Kalpeshbhai Mahadavbhai",
    whatsapp: "9913192023",
    village: "Lelapur",
    taluka: "Lakhtar",
    bloodGroup: "",
    businessName: "Velocity Car Service",
    businessType: "Car Service",
    email: "kalpeshpatel96013@gmail.com",
    website: "",
    address: "Nr. Dav Petroleum Mahendarnagar Chowkdi , Mahendarnagar Morbi-2",
    visitingCard: ""
  },
  {
    fullName: "Lo Amit Kumar Ghanshyam Bhai",
    whatsapp: "9998949366",
    village: "Morbi",
    taluka: "Halvad",
    bloodGroup: "A+",
    businessName: "Bajarang Moters Accersris",
    businessType: "Car 🚗 Motres And Accessories",
    email: "amitpatel11180@gmail.com",
    website: "",
    address: "Mahendrngar Morbi Iti College Ni Same",
    visitingCard: ""
  },
  {
    fullName: "Patel Tusharbhai Bhaveshbhai",
    whatsapp: "8460059828",
    village: "Lakhtar",
    taluka: "Lakhtar",
    bloodGroup: "AB-",
    businessName: "Maruti Sales Agency",
    businessType: "Wholesale Agency",
    email: "tbpatel30798@gmail.com",
    website: "",
    address: "Near Gau Sala Gate Lalper",
    visitingCard: ""
  },
  {
    fullName: "Aravadiya Bharatbhai Keshavjibhai",
    whatsapp: "9979946887",
    village: "Halvad",
    taluka: "Halvad",
    bloodGroup: "O-",
    businessName: "Shree Umiya Roadlines",
    businessType: "Transporter",
    email: "aravadiyab@gmail.com",
    website: "",
    address: "Mehndranagar Chowkdi, Ghuturoad, Morbi",
    visitingCard: ""
  },
  {
    fullName: "Aervadiya Prince Bharat Bhai",
    whatsapp: "7435901517",
    village: "Vaghagadh",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "Shubh Creation",
    businessType: "Clothing (Brand)",
    email: "aervadiyaprince@gmail.com",
    website: "",
    address: "L-579,Opp Bajarang Pan,Sakti Nagar Society,Gujarat Housing Board,Chhatralay Road,Morbi",
    visitingCard: ""
  },
  {
    fullName: "Jaypal Avacharbhai Khavadiya",
    whatsapp: "9727156431",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Deca Micron Pvt Ltd",
    businessType: "Manufacturer Of Calcium Carbonate",
    email: "jaypal.khavadiya89@gmail.com",
    website: "",
    address: "Ahemdabad",
    visitingCard: "https://drive.google.com/open?id=12ICezfmpYMG5LE4pw3BK8dbTRlbrk4qA"
  },
  {
    fullName: "Dilipbhai Thobhanbhai Kaila",
    whatsapp: "9737170007",
    village: "Vaghagadh",
    taluka: "Dhrangdhra",
    bloodGroup: "O-",
    businessName: "Hospital",
    businessType: "Hospital",
    email: "dilipkaila1983@gmail.com",
    website: "",
    address: "Sanala Road,B/H Mahesh Hotel",
    visitingCard: ""
  },
  {
    fullName: "Kandiya Kashyap Nitinbhai",
    whatsapp: "9558368345",
    village: "Lakhtar",
    taluka: "Lakhtar",
    bloodGroup: "AB+",
    businessName: "Gigwell Services Llp",
    businessType: "Service",
    email: "kashyapkandiya9@gmail.com",
    website: "gigwellservices.com",
    address: "Golden Market , Ravaper-Ghunda Road,Morbi",
    visitingCard: ""
  },
  {
    fullName: "Malvaniya Kaushik Maheshbhai",
    whatsapp: "9512444435",
    village: "Sara",
    taluka: "Muli",
    bloodGroup: "O+",
    businessName: "Kaushik M Malvaniya & Associates",
    businessType: "C.A Office",
    email: "kaushikpatel1622000@gmail.com",
    website: "",
    address: "",
    visitingCard: ""
  },
  {
    fullName: "Bapodariya Vijaybhai Ishwarbhai",
    whatsapp: "9979134981",
    village: "Morbi",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Tirupati Water Supplies",
    businessType: "Mineral Water Plant",
    email: "bapodariyajaimin@gmail.com",
    website: "",
    address: "Sakat Sanala",
    visitingCard: ""
  },
  {
    fullName: "Satapara Dhaval Prakashbhai",
    whatsapp: "7046462626",
    village: "Lakhtar",
    taluka: "Lakhtar",
    bloodGroup: "",
    businessName: "Idencis Deaign Studio",
    businessType: "Ceramic Tiles Design Development And All Type Of Branding",
    email: "dhaval007.sd@gmail.com",
    website: "",
    address: "Morbi",
    visitingCard: ""
  },
  {
    fullName: "Kaila Manojbhai Chandubhai",
    whatsapp: "9913442122",
    village: "Vaghadh",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "Monza Granito Pvt Ltd",
    businessType: "Ceramic",
    email: "manojkaila7952@gmail.com",
    website: "",
    address: "151/Pipadi Road, Opp. Vivanta Ceramic, Bela",
    visitingCard: ""
  },
  {
    fullName: "Khavadiya Prince Jayantibhai",
    whatsapp: "9558155606",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Kivana Tradelink",
    businessType: "Feldspar (Soda Potash)",
    email: "princekhavadiya55@gmail.com",
    website: "",
    address: "",
    visitingCard: ""
  },
  {
    fullName: "Vidja Harshad Devkaranbhai",
    whatsapp: "7359655010",
    village: "Jodhapar Nadi",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Maruti Roadways",
    businessType: "Transport,Powdar",
    email: "vidjaharshadd@gmail.com",
    website: "",
    address: "Morbi-2",
    visitingCard: ""
  },
  {
    fullName: "Malvaniya Chintan Ganeshbhai",
    whatsapp: "9033336656",
    village: "Sara",
    taluka: "Muli",
    bloodGroup: "B+",
    businessName: "Shree Hari Account Consultant",
    businessType: "Accounting",
    email: "chintanmalvaniya@gmail.com",
    website: "",
    address: "Arohi Chember3 ,Near Gspc Gas Office",
    visitingCard: ""
  },
  {
    fullName: "Ubhadiya Montu Kumar Vasudev Bhai",
    whatsapp: "9664733477",
    village: "Dhrangadhra",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "Vitrified G.M Job",
    businessType: "Job",
    email: "ubhadiyamontu@gmail.com",
    website: "",
    address: "",
    visitingCard: ""
  },
  {
    fullName: "Arvadiya Jimmy Natvarbhai",
    whatsapp: "7990635652",
    village: "Tikar",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Abdhi Foods",
    businessType: "Wholesaler",
    email: "jimmyarvadiya454@gmail.com",
    website: "",
    address: "Avni Chokdi ,Morbi",
    visitingCard: ""
  },
  {
    fullName: "Dilipbhai Dhanjibhai Sanghani",
    whatsapp: "9904976089",
    village: "Morbi",
    taluka: "Halvad",
    bloodGroup: "O-",
    businessName: "Accounting",
    businessType: "Service",
    email: "dsanghani1970@gmail.com",
    website: "no",
    address: "Shivpark Society Cenal Road Near Nirmal Vidhyalay Opp.Shubhash Nagar Morbi.",
    visitingCard: ""
  },
  {
    fullName: "Talvania Vinodbhai Karshanbhai",
    whatsapp: "9979020311",
    village: "Vaghgadh",
    taluka: "Dhrangdhra",
    bloodGroup: "O+",
    businessName: "Gyanpath Vidhyalay,",
    businessType: "School",
    email: "vkpatelmorbi@gmail.com",
    website: "",
    address: "New Guj.Housing Bord Morbi",
    visitingCard: ""
  },
  {
    fullName: "Khavadiya Harshil Hasmukhbhai",
    whatsapp: "8849140580",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Bahuchar Agro - Mahendranagar",
    businessType: "Wholesaler Of Pesticides & Seeds",
    email: "khavadiyajay55@gmail.com",
    website: "",
    address: "Shop No 4 , Bapa Sitaram Complex , Mahendranagar Chowkdi, Morbi -2",
    visitingCard: "https://drive.google.com/open?id=1Q1GF5GhYO49znB9hGCEMSP_lS9_P-Ks8"
  },
  {
    fullName: "Khavadiya Valabhbhai Audhavjibhai",
    whatsapp: "9714774962",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "B-",
    businessName: "Ceramic Water Suppliers",
    businessType: "Ceramic",
    email: "",
    website: "",
    address: "Dhuva Matel Rode,Morbi",
    visitingCard: "https://drive.google.com/open?id=1Bj51IG5cL0vt9f9kH8d5o7p1DQTKNHwT"
  },
  {
    fullName: "Patel Anand Jivram Bhai",
    whatsapp: "8000029998",
    village: "Shidhasr",
    taluka: "Muli",
    bloodGroup: "",
    businessName: "1) .Aqista Unify Llp  2). Texona Sink Llp",
    businessType: "1).Adhesive Epoxy Grout 2). Qaurtz Sink.",
    email: "patelanand106@gmail.com",
    website: "",
    address: "S.R.No.116, 8-A National Highway Beside",
    visitingCard: ""
  },
  {
    fullName: "Sherasiya Tejash Harji Bhai",
    whatsapp: "9825987870",
    village: "Halvad",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Lambent Nanochemicals",
    businessType: "Nano Chemical , A & C",
    email: "office.lambent@gmail.com",
    website: "www.lambentnanochemicals.com",
    address: "Morbi",
    visitingCard: "https://drive.google.com/open?id=1_jUvnbxP6Gl55q1Fu4_aLE5rYehgACqp"
  },
  {
    fullName: "Fultariya Atulkumar Kanjibhai",
    whatsapp: "9726320567",
    village: "Pratapgarh",
    taluka: "Halvad",
    bloodGroup: "A+",
    businessName: "Space Enterprise",
    businessType: "Diamond Tools And Abrasive",
    email: "space.ent310@gmail.com",
    website: "",
    address: "Shakti Chamber 2, 8 A National Highway, Shop No 33, Morbi",
    visitingCard: "https://drive.google.com/open?id=1jbjqW0SsIQiqPocdszWqYCr2cBgUMZHo"
  },
  {
    fullName: "Detroja Raj Kantilal",
    whatsapp: "7984290515",
    village: "Survadar",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Battery Point",
    businessType: "બેટરી અને ઇન્વર્ટર",
    email: "rajeshpatel9909541101@gmail.com",
    website: "",
    address: "Sky Line Shoping , Near Gspc Gas Office Umiya Circle",
    visitingCard: ""
  },
  {
    fullName: "Andarpa Nilesh Gordhanbhai",
    whatsapp: "9925486284",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Niom Aentarparis",
    businessType: "Cctv Cemera",
    email: "nilesh86284@gmail.com",
    website: "",
    address: "Rangapa",
    visitingCard: ""
  },
  {
    fullName: "Arvadia Hirenkumar Vinodray",
    whatsapp: "9979853049",
    village: "Tikar",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Ashok Industries",
    businessType: "Manufacturing Of Aluminium Section",
    email: "ashok.alu.industries@gmail.com",
    website: "",
    address: "Plot No 223-224, Rafaleshwar Gidc Morbi",
    visitingCard: "https://drive.google.com/open?id=14ECcoCT_2yrjOZDk9RYfFC6rHs0yidXe"
  },
  {
    fullName: "Satapara Pareshkumar Bhavjibhai",
    whatsapp: "8980804196",
    village: "Dholi",
    taluka: "Dhrangdhra",
    bloodGroup: "",
    businessName: "Marutinandan Enterprise",
    businessType: "All Type Of Forklift Spare Parts",
    email: "marutinandanenterprise2024@gmail.com",
    website: "",
    address: "Shop No-13, Shreenath Complex,Near Trajpar Chokdi,Morbi",
    visitingCard: "https://drive.google.com/open?id=1JsyNE_P615I164nFsmbnvZhWaBDojUuZ"
  },
  {
    fullName: "Pragneshkumar Gordhanbhai Patel",
    whatsapp: "9106442025",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Worldworth Corporate",
    businessType: "Ms Steel (Tmt & Structure)",
    email: "alwaysright3298@gmail.com",
    website: "",
    address: "Morbi",
    visitingCard: "https://drive.google.com/open?id=1mIo0mmJoQMH0soais0812qfhkhgTJPBZ"
  },
  {
    fullName: "Vidja Rameshbhai Muljibhai",
    whatsapp: "9825268625",
    village: "Morbi",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Arthwork Jcb",
    businessType: "Machis Bhade Apva Mate",
    email: "",
    website: "",
    address: "Morbi-2",
    visitingCard: ""
  },
  {
    fullName: "Arvadia Vitan Mansukhbhai",
    whatsapp: "7016980865",
    village: "Tikar",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Sunrise Electricals",
    businessType: "Trading Of Industrial Electrical Switchgear",
    email: "sunrise.electricals03@gmail.com",
    website: "",
    address: "Sartanpar Road Near Sunglare Vitrified Morbi-363642",
    visitingCard: "https://drive.google.com/open?id=1iEwP8Qz8cXjFrTmzn4k0CFDFeWYMEjNK"
  },
  {
    fullName: "Gothi Dipakbhai Savjibhai",
    whatsapp: "9979999527",
    village: "Ajitgadh",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Niv Tiles",
    businessType: "Ceramic Trading",
    email: "dipaksgothi@gmail.com",
    website: "",
    address: "Tulshi Chambers Old Ghuntu Road, Trajpar Cross Road, Morbi-363642",
    visitingCard: "https://drive.google.com/open?id=1HfZoaXTlVBJEJqSYtOtbmTgjEXBryBZq"
  },
  {
    fullName: "Bopaliya Rakesh Ratilal",
    whatsapp: "8320875950",
    village: "Vaghgadh",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "Alord Ceramic",
    businessType: "Ceramic Tiles Trading",
    email: "smartboy301189@gmail.com",
    website: "",
    address: "508 Empire Square Opp.Sanora Ceramic Mahendranagar",
    visitingCard: "https://drive.google.com/open?id=1ZSbvI__i_pqBjnS4FIHZbt1zr30TX-xZ"
  },
  {
    fullName: "Serasiya Tejashkumar Harjivanbhai",
    whatsapp: "9825987870",
    village: "Ajitgadh",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Lambent Chemicals",
    businessType: "Chemical Manufacturer",
    email: "tjs.srsy@gmail.com",
    website: "www.lambentnanochemicals.com",
    address: "Morbi",
    visitingCard: "https://drive.google.com/open?id=1ZpE9GmH4HMH1KTCLv0dXBPFk8Bq7CTDZ"
  },
  {
    fullName: "Khavadiya Prabhulal Arjanbhai",
    whatsapp: "9925844722",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Uma Account Associated",
    businessType: "Account",
    email: "prabhukhavadiya@gmail.com",
    website: "",
    address: "2nd Floor, Near Nakshtra Hospital, B/H Kalrav Hospital, Apple Hospital Street, Sanala Road Morbi",
    visitingCard: ""
  },
  {
    fullName: "Bapoliya Rajendrabhai K.",
    whatsapp: "9909459046",
    village: "Vaghgadh",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "Uma Water Saplayarsh",
    businessType: "Harikushn Mogec",
    email: "pr173595@gmail.com",
    website: "",
    address: "Hariom Park Ghuntu.",
    visitingCard: ""
  },
  {
    fullName: "Khavadiya Amit Bhagvanjibhai",
    whatsapp: "9726052004",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "AB+",
    businessName: "Accontant",
    businessType: "Account",
    email: "amitkhavadiya1990@gmail.com",
    website: "",
    address: "Uma Account Associates Near- Nakshtra Hospital Apple Hospital Street Sanala Road Morbi",
    visitingCard: ""
  },
  {
    fullName: "Moradiya Ashokbhai Ramjibhai",
    whatsapp: "9979070805",
    village: "Vankiya",
    taluka: "Halvad",
    bloodGroup: "A+",
    businessName: "Kishan Engineering Works",
    businessType: "Ceramic Lab Machinery Manufacturer",
    email: "ashokrmoradiya@gmail.com",
    website: "https://www.kishaneng.in",
    address: "8-A National Highway,Near Gk Hotel,Trajpar Char Rasta,Morbi-2",
    visitingCard: "https://drive.google.com/open?id=1RIWuEEkzITzuWmWxWn2G1seZKVNJX77V"
  },
  {
    fullName: "Marvaniya Yatin Bhai Tarshi Bhai",
    whatsapp: "8980695958",
    village: "Samli",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Yatin Pack Print",
    businessType: "Packaging",
    email: "yatinmarvaniya@gamil.com",
    website: "",
    address: "Old Ghuntu Road Opp.Zealtop Vitrified",
    visitingCard: "https://drive.google.com/open?id=1prMBRVvy703SojHHbodNQlX0orFu2P4g"
  },
  {
    fullName: "Sanghani Anand Kumar Rameshbhai",
    whatsapp: "7043254745",
    village: "Gujarvadi",
    taluka: "Dhrangdhra",
    bloodGroup: "",
    businessName: "Guru Emporium & Tailor",
    businessType: "Shuting - Shirting",
    email: "sanghanianand6397@email.com",
    website: "",
    address: "Jalaram Complex, Khoja Khana Sheri, Dr. Tkhtshihji Road, Morbi",
    visitingCard: "https://drive.google.com/open?id=1VxgH4-8jwyatSNb9ntpvCAbitEw5Td2k"
  },
  {
    fullName: "Khavadiya Dipak Hansrajbhai",
    whatsapp: "9979071311",
    village: "Krushnanagar (Nava Ratabher)",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Jyoti Art Photography",
    businessType: "Led Screen",
    email: "harshadkhavadiya71311@gmail.com",
    website: "",
    address: "Elora Shopping Opp. New Bus Stand Shanala Road Morbi",
    visitingCard: ""
  },
  {
    fullName: "Varmora Kamleshbhai Parshotambhai",
    whatsapp: "7874000555",
    village: "Sara",
    taluka: "Muli",
    bloodGroup: "B+",
    businessName: "Creations International",
    businessType: "Ceramic Tiles Trading",
    email: "varmorakp3188@gmail.com",
    website: "",
    address: "Shakti Chamber 1",
    visitingCard: ""
  },
  {
    fullName: "Aghara Kishan Hasmukhbhai",
    whatsapp: "8320648660",
    village: "N/A",
    taluka: "N/A",
    bloodGroup: "O+",
    businessName: "Sunplus Cera Llp",
    businessType: "Step Riser & Border Tiles",
    email: "kishanaghara2573@gmail.com",
    website: "",
    address: "Sunplus Cera Llp, Opp.Zibon Ceramic,At Viratnagar , Rangpar",
    visitingCard: ""
  },
  {
    fullName: "Akhara Dasharath Bhai Keshavgi Bhai",
    whatsapp: "9428037637",
    village: "Pratapgarh",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Pioneer Engineering Tools",
    businessType: "Diamond Roller",
    email: "agharadashrath@yahoo.com",
    website: "",
    address: "Old Ghutu Road, Morbi",
    visitingCard: "https://drive.google.com/open?id=1_BPbbTpX9gAWZcxP5O9IQ2YAglhPhli7"
  },
  {
    fullName: "Jignesh Makasana",
    whatsapp: "9924894426",
    village: "Charadava",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Solano Ceramic",
    businessType: "Tiles",
    email: "solanoceramic@gmail.com",
    website: "rsgroupceramic.com",
    address: "Mahendranagar",
    visitingCard: ""
  },
  {
    fullName: "Dalsaniya Jayendra Amrutlal",
    whatsapp: "9825506992",
    village: "Jasapar",
    taluka: "Muli",
    bloodGroup: "B+",
    businessName: "Ganesh Enterprise / R J Moline",
    businessType: "Manufacturing",
    email: "jayu9699@yahoo.com",
    website: "",
    address: "Sakti Chamber / Udaipur / Jaipur",
    visitingCard: ""
  },
  {
    fullName: "Arvadiya Krunal Kumar Jayantilal",
    whatsapp: "8306017917",
    village: "Tikar",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Kemi Pest Control",
    businessType: "Fumigation Service",
    email: "kemipestcontrol@gmail.com",
    website: "",
    address: "Prabhat Chembar, Mahendranagar , Morbi",
    visitingCard: "https://drive.google.com/open?id=18bCr1e7SeapNI0XxZKq69mncBUwFNdFt"
  },
  {
    fullName: "Khavdiya Manoj Bhai Keshvaji Bhai",
    whatsapp: "9925337153",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Loren Ceramic",
    businessType: "Tiles Marketing",
    email: "manojpatel.mp778@gmail.com",
    website: "",
    address: "Old Ghuntu Road Morbi",
    visitingCard: ""
  },
  {
    fullName: "Sanghani Jignesh Maganbhai",
    whatsapp: "9909172742",
    village: "Ravapar Boni Park",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Bajrang Plastic",
    businessType: "Molding",
    email: "sanghanijignesh2750@gmail.com",
    website: "",
    address: "Niyar Patel Transport Manager 1",
    visitingCard: ""
  },
  {
    fullName: "Marvaniya Prakashbhai Prabhubhai",
    whatsapp: "9726916268",
    village: "Vankiya",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Maruti Accounting",
    businessType: "Account Service",
    email: "prakashmarvaniya@gmail.com",
    website: "",
    address: "Jetpar Road, Shubh Corporation Hub,Floor No.5 , Shop No 518,Mahendranagar Morbi",
    visitingCard: ""
  },
  {
    fullName: "Moradiya Niraj Rameshbhai",
    whatsapp: "9512029564",
    village: "Vankiya",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Itoli Granito Llp",
    businessType: "Tiles Manufacturer",
    email: "nirajmoradiya@yahoo.com",
    website: "https://www.itoli.co",
    address: "At:Sartanpar,Dist.:Morbi-363641",
    visitingCard: "https://drive.google.com/open?id=1cC69EzE7W0jQyFZoWK0nZlK_ONFgcNaO"
  },
  {
    fullName: "Khandivar Jitendra Ghoghaji Bhai",
    whatsapp: "9978588188",
    village: "Ingorala",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Aly Microns Llp  & Alystone Microns Llp & Somnath Ceramic",
    businessType: "Soda , Potash Wash Plants",
    email: "jitendrakhandivar918@gmail.com",
    website: "",
    address: "Nichimandal, Morbi Halvad Road",
    visitingCard: ""
  },
  {
    fullName: "Bhoraniyabrijesh",
    whatsapp: "8141458455",
    village: "Morbi",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Lucian Ceramic",
    businessType: "Tiles",
    email: "bhoraniyabrijesh4@gmail.com",
    website: "",
    address: "Old Ghuntu Road Morbi- 2",
    visitingCard: "https://drive.google.com/open?id=1xn8fOjQtmNDxY-k16yqW1ixpCupFIH1v"
  },
  {
    fullName: "Bhavesh R Moradiya",
    whatsapp: "9512029562",
    village: "Vankiya",
    taluka: "Halvad",
    bloodGroup: "A+",
    businessName: "Itoli Granito Llp",
    businessType: "Manufacturing Of Gvt Tiles",
    email: "info@itoli.co",
    website: "www.itoli.co",
    address: "Itoli Granito Llp, Sartanpar Road, Tita Chokdi, Wankaner, Morbi",
    visitingCard: "https://drive.google.com/open?id=1-mZ9doeqYYcjU-zNPVSOi3oyjEPO0jlm"
  },
  {
    fullName: "Makasna Bharatbhai Ambarambhai",
    whatsapp: "9825488866",
    village: "Kadiyana",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Anand Cement Industry",
    businessType: "Coal Business",
    email: "bapatel4@gmail.com",
    website: "",
    address: "Anand Cement Industry, 27 A National Highway, Dhuva Morbi",
    visitingCard: ""
  },
  {
    fullName: "Jotaniya Arvind Bhai Premji Bhai",
    whatsapp: "9979074301",
    village: "Juna Devaliya",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Vm Diamond Tools Squring Whees",
    businessType: "Row Material Of Policing Line",
    email: "arvindbhaijotaniya@gmail.com",
    website: "",
    address: "Morbi2 Trajpar Chokdi",
    visitingCard: ""
  },
  {
    fullName: "Kundariya Maheshbhai Ishwarbhai",
    whatsapp: "9909652282",
    village: "Devipur",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Shree Hari Account",
    businessType: "Accounting",
    email: "sha.consultant111@gmail.com",
    website: "no",
    address: "10 Arohi Chamber 3 Opp Gsps Gas Office, 8 Nha ,Morbi2",
    visitingCard: ""
  },
  {
    fullName: "Patel Bhaveshbhai Jayendrabhai",
    whatsapp: "9978914314",
    village: "Morbi",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Arkiton Ceramic",
    businessType: "Tiles",
    email: "bhaveshkiranpatel@gmail.com",
    website: "",
    address: "Jetpar Road",
    visitingCard: ""
  },
  {
    fullName: "Sitapara Dilip Ishvarbhai",
    whatsapp: "9978554450",
    village: "Tikar",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Ceramic Work",
    businessType: "Body Quality Consultant",
    email: "sitaparadilip1@gmail.com",
    website: "",
    address: "",
    visitingCard: ""
  },
  {
    fullName: "Patel Dilipbhai Ramnikbhai",
    whatsapp: "9925870690",
    village: "Morbi",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Camel Designer Decor",
    businessType: "Decorative Tiles & Pvc Cabinate",
    email: "dilippatel22585@gmail.com",
    website: "",
    address: "Old Ghuntu Road. Morbi",
    visitingCard: ""
  },
  {
    fullName: "Moradiya Mukesh Vashrambhai",
    whatsapp: "7777984657",
    village: "Vankiya",
    taluka: "Halvad",
    bloodGroup: "AB+",
    businessName: "Loren Ceramic",
    businessType: "Tiles Treding",
    email: "mukeshmordiya243@gmail.com",
    website: "",
    address: "Shop No. 10. Swagat Chembar,Old Ghuntu Road Morbi -2",
    visitingCard: ""
  },
  {
    fullName: "Satapara Khodidas Parsottam Bhai",
    whatsapp: "9978173550",
    village: "Dholi",
    taluka: "Dhrangdhra",
    bloodGroup: "O+",
    businessName: "Ceramic Sorting & Packing Contractor",
    businessType: "Contractor",
    email: "khodidaspatel84@gmail.com",
    website: "",
    address: "Morbi",
    visitingCard: ""
  },
  {
    fullName: "Rakesh Bhai Gangaram Bhai Kunpara",
    whatsapp: "9638439321",
    village: "Morbi",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Electric",
    businessType: "Maruti Electric And Inverter Service",
    email: "rp3032734@gmail.com",
    website: "",
    address: "Nani Kenal Road  Sanraiz Vila Shop No 110",
    visitingCard: "https://drive.google.com/open?id=1T4QeT2VJoMWOFo6JWkE5ht9-EGdDOro9"
  },
  {
    fullName: "Agola Manojkumar Ramanik Bhai",
    whatsapp: "8141712877",
    village: "Godavari",
    taluka: "Muli",
    bloodGroup: "B+",
    businessName: "Dispatch Hed",
    businessType: "Job/Service",
    email: "manojpatel81417@gmail.com",
    website: "",
    address: "",
    visitingCard: ""
  },
  {
    fullName: "Mori Kamlesh Natvarlal",
    whatsapp: "9925489087",
    village: "Methan",
    taluka: "Dhrangdhra",
    bloodGroup: "",
    businessName: "Uma Mini Mall Mobile",
    businessType: "Mobile",
    email: "kamleshpatel74755@gmail.com",
    website: "",
    address: "Uma Township Morbi 2",
    visitingCard: ""
  },
  {
    fullName: "Aervadiya Nimesh Rameshbhai",
    whatsapp: "7567217590",
    village: "Morbi",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Food",
    businessType: "Fmcg",
    email: "",
    website: "",
    address: "",
    visitingCard: ""
  },
  {
    fullName: "Patel Jigneshkumar Maganbhai",
    whatsapp: "9909959026",
    village: "Dholi",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "Krivety",
    businessType: "Glaze Raw Material Trading",
    email: "krivety.biz@gmail.com",
    website: "",
    address: "Shop No : 27&28 Seven Cera Mall Near Lords Hotel Jetpar-Pipali Road Morbi-2 363642",
    visitingCard: ""
  },
  {
    fullName: "Parejiya Mukeshbhai Govindbhai",
    whatsapp: "9879492959",
    village: "Dudhrej",
    taluka: "Wadhwan",
    bloodGroup: "B+",
    businessName: "Bajrang Tools",
    businessType: "Carpenter",
    email: "mukeshpatel 7436@gmail.com",
    website: "",
    address: "Ayodhya Puri Main Road Oop Aayush Hospital",
    visitingCard: ""
  },
  {
    fullName: "Bhoraniya Rasiklal Keshavlal",
    whatsapp: "9825051767",
    village: "Juna Devaliya",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Shriji Planning",
    businessType: "Building Planning",
    email: "shrijiplanning@gmail.com",
    website: "",
    address: "Amitpark Society B/H Narsang Temple Ravapar Road Morbi",
    visitingCard: ""
  },
  {
    fullName: "Patel Hitesh Dineshlal",
    whatsapp: "9727770453",
    village: "Goriyavad",
    taluka: "Patadi",
    bloodGroup: "B+",
    businessName: "Wingress Ceramica",
    businessType: "Exporter Of Tiles And Sanitaryware",
    email: "hitesh.wingressceramica@gmail.com",
    website: "www.wingressceramica.com",
    address: "Office No.22, 2nd Floor, Akshar Business Center, Rafadeshwar, At-Jambudia, Morbi - 363642",
    visitingCard: "https://drive.google.com/open?id=10lotnYxbxBdpCyCOrJo5c8SseqDJN-J5"
  },
  {
    fullName: "Aghara Ghanshyambhai Ishvarbhai",
    whatsapp: "9638680005",
    village: "Dhrangadhra",
    taluka: "Dhrangdhra",
    bloodGroup: "",
    businessName: "Mozaca Glass Coat",
    businessType: "Raw Material Frit",
    email: "mozacaglasscoat@gmail.com",
    website: "",
    address: "Jambudiya,Morbi",
    visitingCard: ""
  },
  {
    fullName: "Moradiya Piyush Ghanshyambhai",
    whatsapp: "9909433334",
    village: "Vankiya",
    taluka: "Halvad",
    bloodGroup: "AB+",
    businessName: "Imlis Ceramica Llp",
    businessType: "Ceramic Tiles",
    email: "moradiyapiyush008@gmail.com",
    website: "www.imlis.in",
    address: "Sartanpar Road , Morbi",
    visitingCard: "https://drive.google.com/open?id=1tj_D1bkoGG505DKSKu_8A8DiZBu26Fov"
  },
  {
    fullName: "Moradiya Mukesh Vashrambhai",
    whatsapp: "7777984657",
    village: "Vankiya",
    taluka: "Halvad",
    bloodGroup: "AB+",
    businessName: "Loren Ceramic",
    businessType: "Tiles Trending",
    email: "mukeshmordiya243@gmail.com",
    website: "",
    address: "Swagy Chembar. Shop No-10. Olad Ghuntu Riad Morbi -2",
    visitingCard: ""
  },
  {
    fullName: "Bhoraniya Dineshbhai Durlabhajibhai",
    whatsapp: "9558814014",
    village: "Juna Devaliya",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Umiya Computer World",
    businessType: "Computer Sell & Service",
    email: "umiyacomputerworld@gmail.com",
    website: "www.umiyacomputerworld.com",
    address: "Super Market , Near New Bus Stand , Sanala Road , Morbi",
    visitingCard: "https://drive.google.com/open?id=1OhjKOQgKy8N3DcX2lf_nJjRrQG-PqnaB"
  },
  {
    fullName: "Mayur Manilal Patel",
    whatsapp: "8866339930",
    village: "Goriyavad",
    taluka: "Patadi",
    bloodGroup: "B+",
    businessName: "Titans Ceramic",
    businessType: "Ceramic Trading",
    email: "titansceramic@gmail.com",
    website: "",
    address: "Luxuria Business Park , 427 Office Number, Mahendranagar,Morbi",
    visitingCard: "https://drive.google.com/open?id=1QuGnQBgQAjcPwG1GZt2zxzJdpJ7L83Xu"
  },
  {
    fullName: "Moradiya Bhautik Shantilal",
    whatsapp: "9909433234",
    village: "Vankiya",
    taluka: "Halvad",
    bloodGroup: "AB+",
    businessName: "Imlis Ceramica Llp",
    businessType: "Gvt / Pgvt Tile Manufacturing",
    email: "bhautikmoradiya502@gmail.com",
    website: "https://www.imlis.in",
    address: "Sr No. 173/1 & 174, Sartanpar, Ratavirda Rd, Ratavirda, Gujarat 363621",
    visitingCard: "https://drive.google.com/open?id=1aXU9f9I1kZuo1tUoaxJ4UdW-nWB8MmiS"
  },
  {
    fullName: "Patel Chetanbhai Vinodbhai",
    whatsapp: "9974405744",
    village: "Nava Ghanshyamgadh",
    taluka: "Halvad",
    bloodGroup: "A+",
    businessName: "Latest Garden, Latest Group",
    businessType: "Construction (Builder)",
    email: "chetanvkalariya@gmail.com",
    website: "",
    address: "Mahendra Nagar",
    visitingCard: ""
  },
  {
    fullName: "Agola Sudhir Sanjaybhai",
    whatsapp: "8320827268",
    village: "Navi Kidi",
    taluka: "Halvad",
    bloodGroup: "A-",
    businessName: "Gurukrupa Galas/ Aluminium",
    businessType: "Gurukrupa Galas/ Aluminium",
    email: "sudhiragola@gmail.com",
    website: "",
    address: "Panchasar Road Radhekrishna Ni Same Morbi- 363641",
    visitingCard: ""
  },
  {
    fullName: "Fultariya Hasmukhbhai Kanjibhai",
    whatsapp: "7984951290",
    village: "Pratapgarh",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Squaring Diamond Wheels",
    businessType: "Row Material Of Policing Line",
    email: "smitfultariya67@gmail.com",
    website: "https://www.shreejiimpex.org.in",
    address: "Plot No - 6, Anand Nagar, N.H.27, Trajapar,, Morbi, Gujarat, 363642, India",
    visitingCard: "https://drive.google.com/open?id=1mdZruQDHvt41hqbaWZPl2SHIjMxs4uYK"
  },
  {
    fullName: "Mori Chetan Bhagvanji Bhai",
    whatsapp: "9925983901",
    village: "Methan",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "Patel Pan",
    businessType: "Shop Of Cold Drinks And Pan Masala",
    email: "chetanmori36@gmail.com",
    website: "",
    address: "Makansar(Gokulnagar),Wakaner Highway, Morbi",
    visitingCard: ""
  },
  {
    fullName: "Arvadia Ashishkumar Mansukhbhai",
    whatsapp: "7984935406",
    village: "Tikar",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Sun Electricals",
    businessType: "Trading Of Electrical Switchgear",
    email: "sunelectricals03@gmail.com",
    website: "",
    address: "9/10,Akshar Business Centre,8-A National Highway, Rafadeshwar",
    visitingCard: "https://drive.google.com/open?id=1pY2lMAJSRN9OCACm1OxvH52cTUJzBsBN"
  },
  {
    fullName: "Patel Hirenkumar Jagjivanbhai",
    whatsapp: "9909393387",
    village: "Nagadaka",
    taluka: "Patadi",
    bloodGroup: "B+",
    businessName: "Export Manager",
    businessType: "Job/Service",
    email: "hirenahajoliya@gmail.com",
    website: "",
    address: "",
    visitingCard: "https://drive.google.com/open?id=1wVSQ70Y14tEXJCwD_7CwRIuZm6QT51p-"
  },
  {
    fullName: "Jignesh Patel",
    whatsapp: "9727105031",
    village: "Haripar",
    taluka: "Dhrangdhra",
    bloodGroup: "O+",
    businessName: "Rockstar Truss Light",
    businessType: "Sounds _ Steg Lights  Decorations",
    email: "shreejiliveyou5031@email.com",
    website: "",
    address: "Morbi_ Surat",
    visitingCard: ""
  },
  {
    fullName: "Manoj Bhagavanji Bhai Sitapara",
    whatsapp: "9925258757",
    village: "Tikar",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Tiles Terding   Zeelsun Ceramic",
    businessType: "Ceramic  Terding",
    email: "manojsitapara06@gmail.com",
    website: "",
    address: "Zeelsun Ceramic  ,Shubh Complex  Mhendarnagar Chokadi",
    visitingCard: ""
  },
  {
    fullName: "Sanghani Rakesh Ganeshbhai",
    whatsapp: "9727133592",
    village: "Gujarvadi",
    taluka: "Dhrangdhra",
    bloodGroup: "",
    businessName: "Luck. Fashion And. Tailor",
    businessType: "Cloth. Sutting Shirting And  Redimet",
    email: "rakeshpatel9211@gemail.com",
    website: "",
    address: "Dr.Takhtshihji Rod  Parmanik Show Room Ni Bajuma. Bhagvat Complex",
    visitingCard: ""
  },
  {
    fullName: "Fultariya Ratilal Bachu Bhai",
    whatsapp: "9825583912",
    village: "Pratapgarh",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Packaging Shivautopack",
    businessType: "Corrugated Box",
    email: "shivautopack@gmail.com",
    website: "",
    address: "Survey No 109 P5 Tample Street Jambudiya",
    visitingCard: ""
  },
  {
    fullName: "Hareshbhai Varmora",
    whatsapp: "9979942123",
    village: "Morbi",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Gurukru Waterjet Tiles Cutting",
    businessType: "Customized Tiles Design",
    email: "",
    website: "",
    address: "",
    visitingCard: ""
  },
  {
    fullName: "Methaniya Dhimantbhai Amrutlal",
    whatsapp: "9825467854",
    village: "Sajjanpur",
    taluka: "Dhrangdhra",
    bloodGroup: "",
    businessName: "Savio Ceramica Pvt Ltd",
    businessType: "Ceramic Tiles",
    email: "dapatel67854@gmail.com",
    website: "",
    address: "8 A National Highway",
    visitingCard: ""
  },
  {
    fullName: "Patel Dharmendrabhai Chunibhai",
    whatsapp: "9913672799",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Brilliant School Charadva",
    businessType: "Educational Institute",
    email: "dharmendrapatel269@gmail.com",
    website: "",
    address: "At. Charadva Ta. Halvad",
    visitingCard: ""
  },
  {
    fullName: "Sanghani Ashvinbhai Ganeshbhai",
    whatsapp: "9979451840",
    village: "Gujarvadi",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "Guru Emporium & Tailor",
    businessType: "Sutting &Shirtting",
    email: "aptelp 86@gmai.com",
    website: "",
    address: "Jalaram Complex,Dr.Takhtshinghji Road, Khoja Khana Sheri, Morbi",
    visitingCard: ""
  },
  {
    fullName: "Mahesh Bhai Avchar Bhai Patel",
    whatsapp: "9924860008",
    village: "Ajitgadh",
    taluka: "Halvad",
    bloodGroup: "A+",
    businessName: "Ma Roadlines",
    businessType: "Transport",
    email: "maheshgothi006@gmail.com",
    website: "",
    address: "Mahendra Nagar Chokdi, Hariom Park, Morbi.",
    visitingCard: "https://drive.google.com/open?id=1BdfMYi_9hxrZCxg-q7fiGpmr96RCkXDK, https://drive.google.com/open?id=1sZExv3IIwEv0_uixh3sPYxX5CZXwozbj"
  },
  {
    fullName: "Khavdiya Hasmukhbhai Babubhai",
    whatsapp: "9426449802",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Shree Ram Power Control",
    businessType: "All Led Product Manufacturer, Office Light, Factory Light, Home Light, All Outdoor Lighting, & All Type Electric Item",
    email: "srpc21@yahoo.com",
    website: "",
    address: "1-Lati Plot Near: Krishna Hospital",
    visitingCard: ""
  },
  {
    fullName: "Gadhiya Sunil",
    whatsapp: "9925001510",
    village: "Juna Ghanshyamgadh",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Uma Cab",
    businessType: "Uma Cab",
    email: "sunilpatel25895@gmail.com",
    website: "",
    address: "Mahendranagar Chokdi, Near Cng Pump",
    visitingCard: "https://drive.google.com/open?id=1pDX-HrG4hECCoRAYM53sgeLKtHHK6R8S"
  },
  {
    fullName: "Zalariya Jignesh Jayantilal",
    whatsapp: "9978802177",
    village: "Ranekpar",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Astis Ceramic Llp",
    businessType: "Ceramic Tiles",
    email: "jignesh.astaceramic@gmail.com",
    website: "",
    address: "Khokhada Hanuman Road Bela (Rangpar)",
    visitingCard: "https://drive.google.com/open?id=1dn8xvoCB1-Uiu2wPSOK4t2sna8UKJSsv"
  },
  {
    fullName: "Agola Kamleshbhai Sundarjibhai",
    whatsapp: "8000039794",
    village: "Navi Kidi",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Davanti International Pvt. Ltd.",
    businessType: "Trading",
    email: "davantiinternational@gmail.com",
    website: "",
    address: "Shop. No.5, Swagat Chamber, Near Swagat Ceramic, Old Ghuntu Road, Morbi-Halvad.",
    visitingCard: "https://drive.google.com/open?id=1lCrR74TsCMS0MGaqk4kFs4fpmwpKv7-G"
  },
  {
    fullName: "Patel Mahendra Thobhan Bhai (Bhut)",
    whatsapp: "7046230772",
    village: "Dharmendragadh",
    taluka: "Muli",
    bloodGroup: "O+",
    businessName: "Bahuchar Polymer",
    businessType: "Pp Genual",
    email: "amitzalariya5799@gmail.com",
    website: "bahuchar polymer",
    address: "Lajai",
    visitingCard: "https://drive.google.com/open?id=1jOSCi5VZGBlWz0n2UgzZckrnoG6UEoBd"
  },
  {
    fullName: "Ashvinbhai Rachhadiya",
    whatsapp: "9913564339",
    village: "Katoda",
    taluka: "Wadhwan",
    bloodGroup: "O+",
    businessName: "Rudra Tools Hardware",
    businessType: "Hardware",
    email: "ashvin712@",
    website: "",
    address: "Galaxy Plaza, Umiya Circle, Shanala Road",
    visitingCard: "https://drive.google.com/open?id=1w4KMkQl2eVe8KfgvYFibugPkBhUoCHzd"
  },
  {
    fullName: "Dr. Punita Hiren Sanghani",
    whatsapp: "9737223555",
    village: "Ghanshyamgadh",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Aarav Dental Studio",
    businessType: "Dental Clinic",
    email: "dr.punitapatel@gmail.com",
    website: "",
    address: "Aarav Dental Studio, 32,33 Third Floor, Capital Market, Ravapar Chokadi, Morbi 363641",
    visitingCard: ""
  },
  {
    fullName: "Malvaniya Janak Bhai Shankar Bhai",
    whatsapp: "9638705480",
    village: "Sara",
    taluka: "Muli",
    bloodGroup: "O+",
    businessName: "Bahuchar Polymer",
    businessType: "Pp Granual",
    email: "amitzalriya5799@gmail.com",
    website: "bahuchar polymer",
    address: "Lajai",
    visitingCard: "https://drive.google.com/open?id=191ETWi0C_3WfE5PYUIFKScNZLT8Elqr0"
  },
  {
    fullName: "Jay Patel",
    whatsapp: "9687757000",
    village: "Surendranagar",
    taluka: "Wadhwan",
    bloodGroup: "B+",
    businessName: "Hindgres Ceramica Pvt Ltd",
    businessType: "Ceramic Tile Manufacturers",
    email: "jay@hindgres.com",
    website: "hindgres.com",
    address: "Survey No 115p Makansar 8a National Highway Morbi Gujrat 363641",
    visitingCard: ""
  },
  {
    fullName: "Zalariya Rashminbhai Jayantilal",
    whatsapp: "9898447877",
    village: "Ranekpar",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Asta Ceramic Pvt Ltd",
    businessType: "Manufacturing Of Parking Tiles",
    email: "dr.rjpatel1312@gmail.com",
    website: "",
    address: "Asta Ceramic Pvt Ltd, Opp-Bela Village Pipali Road Morbi",
    visitingCard: ""
  },
  {
    fullName: "Sanghani Dhaval Natvarlal",
    whatsapp: "9099609176",
    village: "Danawada",
    taluka: "Muli",
    bloodGroup: "B+",
    businessName: "Aashvi Enterprise",
    businessType: "Ceramic Machinery Spare Parts.",
    email: "aashvienterprise05@gmail.com",
    website: "",
    address: "Real Plaza,Near Vardhman Hotel Shop No.17",
    visitingCard: ""
  },
  {
    fullName: "Haresh Bhai Mansukh Bhai Varmora",
    whatsapp: "9712345366",
    village: "Sara",
    taluka: "Muli",
    bloodGroup: "O+",
    businessName: "Harikrishna Mojek",
    businessType: "Mojek Tiles Manufacturer",
    email: "hareshpatel5854@gmail.com",
    website: "",
    address: "Pipali Road, Behind Lords Hotel, Morbi.",
    visitingCard: "https://drive.google.com/open?id=15N-GGXSA40AbNjX7RMXkQURAYEu4eA_t"
  },
  {
    fullName: "Dhoriyani Jalpeshbhai Harjivanbhai",
    whatsapp: "7069888401",
    village: "Tikar",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Henshi Motor Rewinding",
    businessType: "Motor Revinding",
    email: "jalpeshpatel2411@gmail.com",
    website: "",
    address: "Matel Road",
    visitingCard: ""
  },
  {
    fullName: "Labkamana Pareshbhai Kanjibhai",
    whatsapp: "7819895195",
    village: "Thala",
    taluka: "Dhrangdhra",
    bloodGroup: "AB+",
    businessName: "Aryan Marketing",
    businessType: "Tiles Showroom Retail And Holsell",
    email: "labkamanaparesh4332@gmail.com",
    website: "www.aryanmarketing.com",
    address: "Marketing Tiles",
    visitingCard: "https://drive.google.com/open?id=1_LLSn2rfCp16gpUS84Kw-fgbCQ2TDusB"
  },
  {
    fullName: "Motka Rajesh Bhai Dayaljibhai",
    whatsapp: "9727632256",
    village: "Mota Ankevaliya",
    taluka: "Dhrangdhra",
    bloodGroup: "AB+",
    businessName: "Sahajanand Electric Store",
    businessType: "Electric Penal",
    email: "rajupatel32256@gmail.com",
    website: "",
    address: "8a National Highway Lalapar",
    visitingCard: "https://drive.google.com/open?id=1Ne3R05qs73FiwNTQvWyxDm9yf6EWveRn"
  },
  {
    fullName: "Labkamana Pareshbhai Kanjibhai",
    whatsapp: "7819895195",
    village: "Thala",
    taluka: "Dhrangdhra",
    bloodGroup: "AB+",
    businessName: "Aryan Marketing",
    businessType: "Tiles Showroom Retail",
    email: "labkamanaparesh4332@gmail.com",
    website: "",
    address: "",
    visitingCard: "https://drive.google.com/open?id=1jNTCAxmi-kshKCuc2M_8eG-DdS2PwBSH"
  },
  {
    fullName: "Mayur Pranbhai Parjiya",
    whatsapp: "8140526865",
    village: "Ranmalpur",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Sarvopari Impex",
    businessType: "Export Wooden Pallets And Packing",
    email: "sarvopariimpex@gmail.com",
    website: "www.sarvopariimpex.com",
    address: "Plot No 1 Survey Number 164 Pipli Village Jetpar Road Morbi",
    visitingCard: ""
  },
  {
    fullName: "Barasara Arvind Nagji Bhai",
    whatsapp: "9909541039",
    village: "Dharmendragadh",
    taluka: "Muli",
    bloodGroup: "B+",
    businessName: "Nachiketa Mashala",
    businessType: "Food Business",
    email: "barasraarvind8 3@gmail.com",
    website: "",
    address: "Sanala Rod , G.I.D.C. , K1-48 ,",
    visitingCard: "https://drive.google.com/open?id=1Em-obTFXvQxy86I-DGqDw1Uj4PyjNif3"
  },
  {
    fullName: "Motka Harshkumar Vasudevbhai",
    whatsapp: "9173336069",
    village: "Mota Ankevaliya",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "Bloflex Surgical Industries",
    businessType: "Syringe Manufacturers",
    email: "bloflexsurgicalind@gmail.com",
    website: "www.bloflex.in",
    address: "Halvad",
    visitingCard: "https://drive.google.com/open?id=1HFa46wKPxBTx6eC9tr0jRidUCFNOYpIv"
  },
  {
    fullName: "Santoki Kaushikkumar Chamanbhai",
    whatsapp: "9726465945",
    village: "Gujarvadi",
    taluka: "Dhrangdhra",
    bloodGroup: "O-",
    businessName: "Elvish Industries",
    businessType: "Hand Made Kitchen Sink",
    email: "kaushik0096@gmail.com",
    website: "www.elvishindustries.com",
    address: "Plot. No . 24/25 ,B/H Vishal Furniture, Near Ambica Engineering",
    visitingCard: "https://drive.google.com/open?id=1z1Kc4s01csCQiS1_FISsUHIQABKH5H5r"
  },
  {
    fullName: "Vamja Karsan Bhai",
    whatsapp: "9724359471",
    village: "Ranmalpur",
    taluka: "Halvad",
    bloodGroup: "O-",
    businessName: "Santkrupa Enterprise And Tiles Cutting",
    businessType: "Treding Tiles",
    email: "dkvamja@gmail.com",
    website: "",
    address: "Halvad Road Uma Residanshi Ni Bajuma",
    visitingCard: ""
  },
  {
    fullName: "Parejiya Nilesh Bhikhalal",
    whatsapp: "9265800719",
    village: "Dudhrej",
    taluka: "Wadhwan",
    bloodGroup: "A+",
    businessName: "Oculus Impex",
    businessType: "Flooring Carpet Treding",
    email: "oculusimpex@gmail.com",
    website: "www.oculusimpex.com",
    address: "Pipli Road, Morbi",
    visitingCard: "https://drive.google.com/open?id=1EYe0Uavyd-nEAbD-DhMOzdpK78R3uJn4"
  },
  {
    fullName: "Padsumbiya Dilip Bhai Prabhu Bhai",
    whatsapp: "9913557075",
    village: "Ishwarnagar",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Shiv Cera Ceramic",
    businessType: "Tiles Trending",
    email: "dilip.qubictiles@gmail.com",
    website: "",
    address: "Kaka Chembar Shop -9 B/H Vishal Furniture",
    visitingCard: ""
  },
  {
    fullName: "Aghara Pravin Bhai Shivlal Bhai",
    whatsapp: "9879456366",
    village: "Ishwarnagar",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Kishan Computer",
    businessType: "Accountant",
    email: "infokishancom@gmail.com",
    website: "",
    address: "Ilora Shoping, Behind Hotel Manali, Opp. New Bus Stand, Sanala Road, Morbi.",
    visitingCard: "https://drive.google.com/open?id=1TMA6H_yGSmGEV_zlvT4JLH3-HSpDbHbI"
  },
  {
    fullName: "Gadhiya Mansi Kamleshbhai",
    whatsapp: "8140024382",
    village: "Dhulkot",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Gadhiya Interior Design Studio",
    businessType: "All Types Of Interior Design",
    email: "gadhiyainterior@gmail.com",
    website: "",
    address: "Gayatri Nagar 1 , Block No 48 , Ravapar Road , Near Umiya Chock , Morbi",
    visitingCard: "https://drive.google.com/open?id=1x6vEYIvUV-O_fNZOcqzgSyZdRXg7SwsL, https://drive.google.com/open?id=1LsnjmaNjm8jTPL3pTOUDXT5MP64aEOCe"
  },
  {
    fullName: "Surani Vijaykumar Ratilal",
    whatsapp: "9638916304",
    village: "Survadar",
    taluka: "Halvad",
    bloodGroup: "A+",
    businessName: "Ignite Paper",
    businessType: "Manufacturer",
    email: "ignitepapers2023@gmail.com",
    website: "www.ignitepaper.com",
    address: "Hadmatiya Road Lajai Chokadi",
    visitingCard: "https://drive.google.com/open?id=12_TTnNSmJsNB_Y0hUlYgNj5nMSu_JYTa"
  },
  {
    fullName: "Patel Satishbhai Tribhovanbhai",
    whatsapp: "9726529905",
    village: "Dhrangadhra",
    taluka: "Dhrangdhra",
    bloodGroup: "AB+",
    businessName: "Shiv Electricals And Rewinding",
    businessType: "Make Arc Welding Machine",
    email: "sp8857206@gmail.com",
    website: "",
    address: "Opposite Ramdhan Aashram Shop No. 11 Mahendra Nager Road, Morbi 2",
    visitingCard: ""
  },
  {
    fullName: "Patel Satishbhai Tribhovanbhai",
    whatsapp: "9726529905",
    village: "Dhrangadhra",
    taluka: "Dhrangdhra",
    bloodGroup: "AB+",
    businessName: "Shiva Electricals And Rewinding",
    businessType: "Make Arc Welding Machine",
    email: "sp8857206@gmail.com",
    website: "",
    address: "Oppo. Ramdhan Aashram Shop No. 11,Morbi2 Mahendra Nagar Road",
    visitingCard: ""
  },
  {
    fullName: "Hulani Anil Bhai Baldev Bhai",
    whatsapp: "9913758097",
    village: "Mangadh",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Harikrishna Febrikesan",
    businessType: "Harikrishna Febrikesan",
    email: "",
    website: "",
    address: "Mahendra Nagar",
    visitingCard: ""
  },
  {
    fullName: "Patel Satishbhai Tribhovanbhai",
    whatsapp: "9726529905",
    village: "Dhrangadhra",
    taluka: "Dhrangdhra",
    bloodGroup: "AB+",
    businessName: "Shiv Electricals And Rewinding",
    businessType: "Make Arc Welding Machine",
    email: "sp8857206@gmail.com",
    website: "",
    address: "Opposite Ramdhan Aashram,Morbi 2,Shop No.2,Mahendra Nagar Road",
    visitingCard: ""
  },
  {
    fullName: "Patel Satishbhai Tribhovanbhai",
    whatsapp: "9726529905",
    village: "Dhrangadhra",
    taluka: "Dhrangdhra",
    bloodGroup: "AB+",
    businessName: "Shiv Electricals And Rewinding",
    businessType: "Make Arc Welding Machine",
    email: "sp8857206@gmail.com",
    website: "",
    address: "Opposite Ramdhan Aashram Morbi 2 Shop No.11, Mahendra Nagar Road",
    visitingCard: ""
  },
  {
    fullName: "Varmora Divyang Vallabhbhai",
    whatsapp: "9825797977",
    village: "Sara",
    taluka: "Muli",
    bloodGroup: "A+",
    businessName: "Shree Royal Polyplast Industries",
    businessType: "Manufacturing",
    email: "divyang.varmora@yahoo.com",
    website: "www.royalpolyplast.com",
    address: "Morbi - Navlakhi Highway, Pipaliya Char Rasta,",
    visitingCard: ""
  },
  {
    fullName: "Gothi Jitendrabhai Savjibhai",
    whatsapp: "9879329266",
    village: "Ajitgadh",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Hariom Ceramic",
    businessType: "Ceramic Tiles Trading",
    email: "hariomceramic@gmail.com",
    website: "",
    address: "First Floor,  Office No. 16, Tulshi Chambers, Old Ghuntu Road, Trajpar Cross Road, Morbi-363642 (Gujarat) India",
    visitingCard: ""
  },
  {
    fullName: "Pravin Bhai Moradiya",
    whatsapp: "9925726346",
    village: "Morbi",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Lucian Ceramic",
    businessType: "Ceramic Tiles",
    email: "moradiyapravin954@gmail.com",
    website: "lucian ceramic",
    address: "Yogesh Potri,Old Ghutu Road, Morbi-2",
    visitingCard: ""
  },
  {
    fullName: "Desai Sureshbhai Gandubhai",
    whatsapp: "9925675554",
    village: "Survadar",
    taluka: "Halvad",
    bloodGroup: "AB+",
    businessName: "Shri Ji Aluminium Shop",
    businessType: "Door Making",
    email: "sd4639767@gmail.com",
    website: "",
    address: "Mahendranagar-- Near Krantijyot Park -- Super Market 2 - Shop Number 6",
    visitingCard: ""
  },
  {
    fullName: "Patel Satishbhai Tribhovanbhai",
    whatsapp: "9726529905",
    village: "Dhrangadhra",
    taluka: "Dhrangdhra",
    bloodGroup: "AB+",
    businessName: "Shiv Electricals And Rewinding",
    businessType: "Make Arc Welding Machine",
    email: "sp8857206@gmail.com",
    website: "",
    address: "Opposite Ramdhan Aashram, Shop No.11, Morbi 2 Mahendranagar Road",
    visitingCard: "https://drive.google.com/open?id=1ewonqdRQG_KDxUznvM0DZvjLMa4vCMtS"
  },
  {
    fullName: "Dethariya Harshad Jethabhai",
    whatsapp: "9099241436",
    village: "Tikar",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Dethariya Modular Solution",
    businessType: "Modular Kitchen",
    email: "hjdethariya888@gmail.com",
    website: "",
    address: "K-1/77 Gidc, Sanala Road, Near Krishna Bakery, Morbi",
    visitingCard: "https://drive.google.com/open?id=1oUnFcth7uz8S0ikBU6mjKxaQf2Lgze9B"
  },
  {
    fullName: "Khavadeeya Chetankumar Ratanshibhai",
    whatsapp: "8469067870",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Grindelwald Corporation",
    businessType: "Plastic Corner Manufacturer",
    email: "grindelwaldcorporation@gmail.com",
    website: "",
    address: "Bhadiyad. Morbi, Gujarat, India.",
    visitingCard: "https://drive.google.com/open?id=1PHsN1qQQOarh_HDbFupD_W0-jwsj840A"
  },
  {
    fullName: "Keraliya Nirav Bhagvatbhai",
    whatsapp: "9979375602",
    village: "Mahendrnagar",
    taluka: "Halvad",
    bloodGroup: "AB+",
    businessName: "Thakardhani Refrigerator",
    businessType: "Freez Service And Repairing",
    email: "nbkeraliya056@gmail.com",
    website: "",
    address: "Mahendrnagar Ghutu Road, Shyam Park Same, Shivshakti Complex-1, Shop No. 10",
    visitingCard: "https://drive.google.com/open?id=1fulZqgXldi6RP5QXSqPqmHxZO3oT1SKC"
  },
  {
    fullName: "Kaila Pruthvik Dipakbhai",
    whatsapp: "7818851505",
    village: "Halvad",
    taluka: "Halvad",
    bloodGroup: "AB-",
    businessName: "Supraanti India",
    businessType: "Education, Import-Export, Digital Marketing",
    email: "supraanti.export@gmail.com",
    website: "https://supraantiindia.com/",
    address: "4th Floor, Above Sanket India, Umiya Circle, Sanala Road, Morbi - 363641, Gujarat, India",
    visitingCard: ""
  },
  {
    fullName: "Vadhrodiya Rajesh Mansukhbhai",
    whatsapp: "9724570138",
    village: "Halvad",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Sitara Microns",
    businessType: "All Types Of Ceramic Row Material",
    email: "sitaramicrons@gmail.com",
    website: "",
    address: "Opp. Uhchi Mandal, Nr. Marbilano Surface,Talavaiya Sanala Road, Morbi-363641",
    visitingCard: "https://drive.google.com/open?id=1mDje2WX8FstXilMlY7GxMmeeXkAHLrl1"
  },
  {
    fullName: "Aghara Hiteshbhai Ramjibhai",
    whatsapp: "9898235577",
    village: "Juna Devaliya",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Patidar Enterprise",
    businessType: "Trading Of 3m Scotchbrites For Sanitarywares, Wide Sanding Belts For Laminates And Others Finsihing Products.",
    email: "patidarenterprise23@gmail.com",
    website: "",
    address: "Office-A, Lalpar Industrial Estate - 1, Plot No.14, 8-A, N.H., Lalpar, Morbi-363642.",
    visitingCard: "https://drive.google.com/open?id=1iPdXtt08e_guJGoU5-EFjG_s3tMsk67S"
  },
  {
    fullName: "Ughareja Prahladbhai Amrutbhai",
    whatsapp: "7041212121",
    village: "Vaghgadh",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "Shivam Multispecility Hospital,  Morbi 2",
    businessType: "Orthopedic Surgeon",
    email: "drprahladughareja@gmail.com",
    website: "",
    address: "Shivam Multispecialty Hospital Mahendranagar Road Morbi - 2",
    visitingCard: "https://drive.google.com/open?id=1cXetCDNhsE17mP_1qxmp9ByxsZLhSued, https://drive.google.com/open?id=1TYvGV591HDpwGrSL0BAg1VWxZwJpHuqz"
  },
  {
    fullName: "Aervadiya Chiragbhai Rajeshbhai",
    whatsapp: "9638834394",
    village: "Tikar",
    taluka: "Halvad",
    bloodGroup: "AB+",
    businessName: "Holo Sanitaryware Pvt Ltd",
    businessType: "Manufacturing Of Sanitaryware Products",
    email: "",
    website: "https://holosanitaryware.com/",
    address: "Survey No.723 P3, 724 1 Paiki 1, 724 1 Paiki 2, Old Ghuntu Rd, Near Evernew Paper Mill, Lakhdhirpur, Morbi, Ghuntu, Gujarat 363642",
    visitingCard: "https://drive.google.com/open?id=1-43T5HlzAvYfiV46EsCC_zBIu0hZ1YCr"
  },
  {
    fullName: "Dethariya Kishan Mansukhbhai",
    whatsapp: "8306039418",
    village: "Tikar",
    taluka: "Halvad",
    bloodGroup: "B-",
    businessName: "Bhagvati Clinic",
    businessType: "Doctor",
    email: "1234kishandethariya@gmail.com",
    website: "",
    address: "Bhagvati Clinic,Dhuva Chokdi, Matel Road Morbi",
    visitingCard: "https://drive.google.com/open?id=1rdvyiTFzkyzsy3QhCw-SHwZ8R1EW_5V9"
  },
  {
    fullName: "Arvadiya Dhawal Bhai Raghavji Bhai",
    whatsapp: "9825802100",
    village: "N/A",
    taluka: "N/A",
    bloodGroup: "B-",
    businessName: "Jay Muralidhar Travels",
    businessType: "Tours & Travels",
    email: "dhawalpatel13215@gmail.com",
    website: "",
    address: "6-7 Lati Plot Main Road Morbi",
    visitingCard: ""
  },
  {
    fullName: "Gopani Lalitbhai Savjibhai",
    whatsapp: "9725280500",
    village: "Nava Ghanshyamgadh",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Maruti Motors",
    businessType: "Car Repair",
    email: "prayaggopani28@gmail.com",
    website: "",
    address: "Behind Limda Vala Meldi Mataji Temple, Morbi - Rajkot Highway, Shakti Sanala, Morbi.",
    visitingCard: ""
  },
  {
    fullName: "Moradiya Ashok Bhai Ramji Bhai",
    whatsapp: "9979070805",
    village: "Vankiya",
    taluka: "Halvad",
    bloodGroup: "A+",
    businessName: "Kishan Engineering Works",
    businessType: "Workshop (M D M E)",
    email: "ashokrmoradiya@gmail.com",
    website: "",
    address: "8-A N.H. Near G.K. Hotel Trajpar Chokdi Morbi -2",
    visitingCard: "https://drive.google.com/open?id=1u3YI2aFGtcIWhdeqvyUuQbfamXyVQc1o, https://drive.google.com/open?id=1DZrmfsvBD7i_bjGfcG06fvOFjohSqJzj"
  },
  {
    fullName: "Jayesh M Patel",
    whatsapp: "9924833860",
    village: "Limbadi",
    taluka: "Limbadi",
    bloodGroup: "AB+",
    businessName: "Khodiyar Auto Garege",
    businessType: "Bike Survice &Repering",
    email: "pateljayesh99248@gmail.com",
    website: "",
    address: "Super Market 2 Behind  Mahendranagar Busstand Shop No16",
    visitingCard: ""
  },
  {
    fullName: "Araniya Jitendar Bhai Narayan Bhai",
    whatsapp: "9537899321",
    village: "Tikar",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Moment Technology",
    businessType: "Cctv Camera All",
    email: "areniyajitendar@gmail.com",
    website: "",
    address: "Mhedarnagar Morbi 2",
    visitingCard: "https://drive.google.com/open?id=1KhYdWrRhqogG3Q1Fv3MGXMODG2IfStfo"
  },
  {
    fullName: "Jakasaniya Hardikkumar Girdharlal",
    whatsapp: "8140162624",
    village: "Rajcharadi",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "Excellent Consultancy",
    businessType: "Gst Consultanct And Tax Adviser",
    email: "excellentmorbi@gmail.com",
    website: "",
    address: "S-19, Super Market-2, Near Krantikjyot Park, Opp. Prabhukrupa Township, Mahendranagar, Morbi",
    visitingCard: "https://drive.google.com/open?id=169wo-zuVvH5jceMESaQv9Dn5_qJ0-KVL, https://drive.google.com/open?id=1rLCw8dxUBqiPuIOGaBFWB5f8I5fkBDNk"
  },
  {
    fullName: "Butani Sachinhareshbhai",
    whatsapp: "7069506626",
    village: "Khajeli",
    taluka: "Wadhwan",
    bloodGroup: "B+",
    businessName: "Auralam Laminates Llp",
    businessType: "Manufacturing",
    email: "sbutani04@gmail.com",
    website: "auralamlaminates.com",
    address: "Survey No. 164/5,Opp. Sarvoday Hotel, Nh - 8a, Juna Sadulka, Morbi, Gujarat(India).",
    visitingCard: "https://drive.google.com/open?id=1R3ZGbte9LtrUQAIfoG4DQD4whMFl6n07"
  },
  {
    fullName: "Chhaniyara Manoj Chandubhai",
    whatsapp: "9979911100",
    village: "Nava Ghanshyamgadh",
    taluka: "Halvad",
    bloodGroup: "A+",
    businessName: "Million Ceramic",
    businessType: "Ceramic Wall Tiles",
    email: "manojpatel161187@gmail.com",
    website: "",
    address: "8-A, National Highway, At-Dhuva,",
    visitingCard: "https://drive.google.com/open?id=1UWwtmUVnqI8ktvwo3JYccuZmDsDsYfJg, https://drive.google.com/open?id=1sJj_m9-kGX4RYy5dGm5HA4OEsoVDrQ0Q"
  },
  {
    fullName: "Dalsaniya Preet Dhanjibhai",
    whatsapp: "6356321115",
    village: "N/A",
    taluka: "N/A",
    bloodGroup: "",
    businessName: "Oryn Minchem",
    businessType: "Bopp Tape",
    email: "preetdalsaniya2046@gmail.com",
    website: "",
    address: "Morbi",
    visitingCard: ""
  },
  {
    fullName: "Arvadiya Hiren Lalitbhai",
    whatsapp: "9277404603",
    village: "Tikar",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Pavan Computer",
    businessType: "All Type Of Computer Jobwork, Election Card New,  Election Card Correction,  Driving Licence New, Driving Licence Renew, Passport, All Type Of Computer Job Work And Rto Work",
    email: "pavancomputer4603@gmail.com",
    website: "",
    address: "Pavan Computer, Golden Point, First Floor, Near High Way Jakat Naka, Jinpara, Wankaner",
    visitingCard: "https://drive.google.com/open?id=10vNIqGw17I7socW2prMymwJ7ogs5Hjdc"
  },
  {
    fullName: "Khavadeeya Kaushik Pravinbhai",
    whatsapp: "9638103777",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Maamantchemico Llp",
    businessType: "Pvc And Plastic Additives And Speciality Chemical, Also Paint And Rubber Additives.",
    email: "info@maamantra.com",
    website: "www.maamantra.com",
    address: "Plot 107, Shreeji Estate, Sanala Byepass, Morbi-363641.",
    visitingCard: "https://drive.google.com/open?id=1yY-wVo-VsssPeBisZfsXBLOvALyBNsaS"
  },
  {
    fullName: "Bhoraniya Hiteshbhai Dayabhai",
    whatsapp: "9978102862",
    village: "Morbi",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Krishna Engineering And Mechanical",
    businessType: "Piston Air Compressor Sels And Services & All Type Of Water Pump Services & Gear Box Services",
    email: "krishanaeng789@gmail.com",
    website: ".",
    address: "Old Ghutu Road, Near Yogesh Potry, Morbi 2",
    visitingCard: "https://drive.google.com/open?id=14fM8d9uucylnTjZtapYROTUmQm6UAFaq"
  },
  {
    fullName: "Ashokbhai Ramjibhai Mordiya",
    whatsapp: "9979070805",
    village: "Vakiya",
    taluka: "Halvad",
    bloodGroup: "A+",
    businessName: "Kishan Engineering Works",
    businessType: "Workshop",
    email: "ashokrmordiya@gmail.com",
    website: "",
    address: "Tajpar Chokadi Near G K Hotel 8-A National Highway,Morbi",
    visitingCard: ""
  },
  {
    fullName: "Vishal Motka",
    whatsapp: "8866590300",
    village: "Manpur",
    taluka: "Dhrangdhra",
    bloodGroup: "O+",
    businessName: "Airson Plaster Product& Airson Packaging",
    businessType: "Plot No 5,Om Industrial Estate Near Khokhara Hanuman Temple Bela",
    email: "vishal.motka@gmail.com",
    website: "",
    address: "",
    visitingCard: "https://drive.google.com/open?id=1DEDuEsAQuI-LEUXDj1RUPkUQMpfoVICK"
  },
  {
    fullName: "Arvinbhai Rachadiya",
    whatsapp: "9913580741",
    village: "Katuda",
    taluka: "Wadhwan",
    bloodGroup: "O+",
    businessName: "Rudra Power Tools & Hardware",
    businessType: "Personal",
    email: "",
    website: "",
    address: "Galaxy Plaza Umiya Circle Sanala Road ,Morbi",
    visitingCard: "https://drive.google.com/open?id=13mi4HR7_F4sS8zDJhmFYUNgAbXjuWoOH"
  },
  {
    fullName: "Arvadiya Raviraj Sanjaykumar",
    whatsapp: "7990688364",
    village: "Tikar",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Jagdamba Construction",
    businessType: "Personal Business",
    email: "hitech.planing@gmail.com",
    website: "",
    address: "Laxmi Plaza, Second Floor,Shop No 3, Sanala Road, Morbi",
    visitingCard: "https://drive.google.com/open?id=1XQE_FG_Vv04nLxzqYNIBEhUaTqQJdTQh"
  }
];
